### ISSUE TITLE
MS-DOS ERROR: fatfs write ignored

### ISSUE THREAD

**Issue by kmm2** [dosemu2/dosemu2#1181]
I'll gladly get rid of MS-DOS and use only open-source.
_Originally posted by @kmm2 in https://github.com/dosemu2/dosemu2/issues/1145#issuecomment-635933621_

Yes I wrote it but I'd like to have an option of running MS-DOS for tests and performance comparisons to fdpp. It worked fine in dosemu2 6123 but no more in 6125:

ERROR: fatfs write ignored: dir /home/a/.dosemu/drive_c, sec 18969, len 2

My current setup
```

dosemu2/bionic,now 2.0~pre8-6125-f8fb7ac+202005282337~ubuntu18.04.1 amd64 [installed]
fdpp/now 1.0~rc2-1001-05a3b52+202005291024~ubuntu18.04.1 amd64 [installed,local]
fdpp-dbgsym/now 1.0~rc2-1001-05a3b52+202005291024~ubuntu18.04.1 amd64 [installed,local]
```

[boot.log](https://github.com/dosemu2/dosemu2/files/4704988/boot.log)

**Comment by stsp** [comment]
What version of ms-dos?
What is your config and autoexec?
What command.com do you use,
is it standard from ms-dos?
Have you changed any dosemu
settings?

**Comment by kmm2** [comment]
I described it here https://github.com/dosemu2/dosemu2/issues/1145#issuecomment-635013452
- no autoexec
- no dosemu changes
- standard, original MS-DOS

```
COMMAND.COM
CONFIG.SYS
HIMEM.SYS
IO.SYS
MSDOS.SYS
```
Basically, the database app now works with fdpp but no more with MS-DOS 6.
MS-DOS starts up OK but the app, under MS-DOS, produces the errors and finally stops and freezes.

**Comment by stsp** [comment]
Can the problem be reproduced without
your database, by simply doing eg
copy himem.sys himem.bak
to trigger any disk write?
If so - please pack your drive_c
(only with boot files, no need for
database) and upload it here.

**Comment by kmm2** [comment]
Yes, just "dir > dir.txt" write produces:
```
ERROR: fatfs write ignored: dir /home/a/.dosemu/drive_c, sec 503, len 1
ERROR: fatfs write ignored: dir /home/a/.dosemu/drive_c, sec 27223, len 1
ERROR: fatfs write ignored: dir /home/a/.dosemu/drive_c, sec 2, len 1
ERROR: fatfs write ignored: dir /home/a/.dosemu/drive_c, sec 253, len 1
ERROR: fatfs write ignored: dir /home/a/.dosemu/drive_c, sec 27224, len 1
ERROR: fatfs write ignored: dir /home/a/.dosemu/drive_c, sec 503, len 1
```
[drive_c-dos6.zip](https://github.com/dosemu2/dosemu2/files/4705514/drive_c-dos6.zip)

**Comment by stsp** [comment]
Can't reproduce:
```
C:\>dir >a.txt
C:\>dir
 Volume in drive c is EMU DRIVE_C
 Directory of c:\
 
2020-05-30 14:11 <DIR>         TMP
2020-05-30 14:11           219 A.TXT
         1 file(s)            219 bytes
         1 dir(s)               0 byte(s) free
C:\> 
```

You changed some settings.

**Comment by stsp** [comment]
Ignore the above, need to try again...

**Comment by stsp** [comment]
No, can't reproduce, this time for real:
```
Microsoft(R) MS-DOS(R) Version 6
             (C)Copyright Microsoft Corp 1981-1993.
 
C:\>dir >a.txt
 
C:\>dir
 
 Volume in drive C is EMU DRIVE_C
 Directory of C:\
 
CONFIG   SYS        82 05-26-20  12:10p
TMP          <DIR>     05-30-20   2:11p
MSDOS    SYS     38138 03-10-93   6:00a
HIMEM    SYS     14208 03-10-93   6:00a
A        TXT       422 05-30-20   2:13p
IO       SYS     40470 03-10-93   6:00a
COMMAND  COM     52925 03-10-93   6:00a
        7 file(s)     146245 bytes
                  2147450880 bytes free
 
C:\>
```

**Comment by kmm2** [comment]
I rebooted it, removed dosemu, reinstalled it, but the error still persists. New install:
```
fdpp/bionic,now 1.0~rc2-1002-52acbb7+202005301017~ubuntu18.04.1 amd64 [installed,automatic]
dosemu2/bionic,now 2.0~pre8-6125-f8fb7ac+202005282337~ubuntu18.04.1 amd64 [installed]
```

**Comment by stsp** [comment]
> I rebooted it, removed dosemu

How?
Just uninstall won't clean everything.
You need purge

**Comment by kmm2** [comment]
I see, I'll redo it. Also, can I get 6123 somehow?

**Comment by kmm2** [comment]
I did apt-get purge dosemu2
deleted /home/a/.dosemu
Re-tried, still the MS error, fdpp works fine.

**Comment by stsp** [comment]
Please post the `-D9+cDi#` log.

**Comment by kmm2** [comment]
How can I make the -D9+cDi# log? Sorry, not familiar with it.

I can assure you that the problem is reproducible. On a completely different PC/Linux which has never seen dosemu before I did basic:

- sudo add-apt-repository ppa:dosemu2/ppa
- sudo apt update
- sudo apt install dosemu2

Then copied MS DOS and tried dir write, got the error.

**Comment by stsp** [comment]
By running `dosemu -D9+cDi#` its that simple.

**Comment by andrewbird** [comment]
I find it strange why `dir >  a.txt` produces fatfs errors as I would expect MFS to be the filesystem in use and @stsp's paste shows it is for him. So my question is was MFS not mapped, was it unmapped with lredir or did CDS become corrupt?

**Comment by stsp** [comment]
I think the command.com hook didn't
work for whatever reason.

**Comment by stsp** [comment]
If this is the recent regression, then
the only possible commit that could
affect it, is this one:
https://github.com/dosemu2/dosemu2/commit/9068c5328e72f84ac209282988c4de80c2401459
But I can't see anything wrong with
it. So lets wait for a logs.

**Comment by kmm2** [comment]
The 9068c53 was "committed 10 days ago "
I'm using dosemu2 6125 20200528 - 3 days old, the issue is from a newer commit.
Have you tried it on a brand new Linux instance with fresh ppa install? The error is reproducible.

Here is  [boot.log.gz](https://github.com/dosemu2/dosemu2/files/4706783/boot.log.gz)  when MS error happens.

**Comment by stsp** [comment]
Thanks.
Please do `-D9+cDi#d` log.

**Comment by stsp** [comment]
OK, no need.
I've found the problem in the log.
Why didn't you show this msg from terminal?
`ERROR: KVM: error opening /dev/kvm: No such file or directory`

**Comment by stsp** [comment]
Bart, could you please see why 6f16dbf30
breaks int_revectored on JIT?

**Comment by kmm2** [comment]
> Why didn't you show this msg from terminal?
> ERROR: KVM: error opening /dev/kvm: No such file or directory

but it is in the log of my opening post already

**Comment by stsp** [comment]
> but it is in the log of my opening post already

Yes, and I missed it there, BUT, it is also on
your terminal! Whatever errors you have on
terminal, must be immediately copied here,
as they are most important.

Anyway, should now be fixed.

**Comment by kmm2** [comment]
not yet, I upgraded to 6129-75fb345+202005302302 and the error still persists

**Comment by stsp** [comment]
LP is updated daily.
Not a big deal to forcibly update.
Re-check tomorrow.

**Comment by kmm2** [comment]
Thank you, I'll check it tomorrow.
Meanwhile, can you help me with dbgsym?
I can download and install it manually but I'd prefer ppa install.
I have followed this [info](https://wiki.ubuntu.com/DebuggingProgramCrash) precisely but I still can't install it...
```
apt install fdpp-dbgsym
E: Unable to locate package fdpp-dbgsym

apt install fdpp-dbgsym=1.0~rc2-1002-52acbb7+202005301017~ubuntu18.04.1_amd64
E: Unable to locate package fdpp-dbgsym
```

**Comment by stsp** [comment]
sudo apt-get update

**Comment by kmm2** [comment]
sure, done that but still no success

**Comment by stsp** [comment]
It seems you need to go to `/etc/apt/sources.list.d`
and grep the files there for the line
`deb http://ppa.launchpad.net/dosemu2/ppa/ubuntu YOUR_UBUNTU_VERSION_HERE main`
Then you should add a similar line with
the component changed from "main" to "main/debug".
Then `sudo apt-get update`.
At least that's what the manual says.
I rebuilt the packages on PPA with the fix.

**Comment by kmm2** [comment]
Thank you, with your instructions dbgsym works. The other instructions referred to non-ppa debug and that's why didn't work for me.

Yes, the rebuilt package fixed the problem indeed.

Now with MS-DOS and fdpp both OK, I compared the database's performance.
Unfortunately fdpp is 5x slower than MS-DOS on reindexing the database.
Even simple dos-deleting of say 200 files is much slower than MS.
Please create a few hundred files and compare the delete speed.
If you wish I can upload a data-empty version of the database (0.7MB zip).

**Comment by stsp** [comment]
fdpp is supposed to be slower as it
have to always switch to protected
mode and back. But I never thought
it can become a bottle neck.
Please upload your tests to fdpp
tracker and I'll see if maybe something
can be done.

**Comment by andrewbird** [comment]
I wonder if it's because FDPP has file sharing built in now, does your test on MS-DOS also have share.exe loaded?

**Comment by kmm2** [comment]
No SHARE.EXE. Apart from the database app, I created 1000 files with `for /l %a in (1,1,1000) do echo %a > %a.tmp` and copied them to dosemu. Already 'dir' command is visibly slower in fdpp, and del *.tmp takes 1sec in MS-DOS6 and 10sec in fdpp. I'm now looking for a dos file I/O benchmark app.

**Comment by stsp** [comment]
comcom32 is very slow.
You can put freecom.exe as
command.com to C and get faster
file operations with fdpp.

**Comment by kmm2** [comment]
Incidentally, after the successful MS error fix, I still see:

`ERROR: KVM: error opening /dev/kvm: No such file or directory`

but everything works, ignore?

**Comment by andrewbird** [comment]
It means either you haven't installed `qemu-kvm` or added yourself into the kvm group. Try this from the Wiki:
~~~
sudo apt install qemu-kvm
sudo adduser `id -un` kvm
~~~
Then log out and back in (to collect the new group membership), and try again

**Comment by kmm2** [comment]
Qemu is a completely different emulator project. Why do I need to install it?
Secondly, why the absence of Qemu could have caused [the error](https://github.com/dosemu2/dosemu2/issues/1181#issuecomment-636405605)?

**Comment by andrewbird** [comment]
That would only install the kvm component of qemu, which does the setup of the kvm module for us. Obviously you could do that by hand, but if you also wish to use qemu at some point it's best to do it in a compatible way by sharing the same permissions / ownership on the `/dev/kvm` device file.

>  Secondly, why the absence of Qemu could have caused the error?

It didn't but it meant, as now, your Dosemu is using its software emulator. Stas hadn't spotted that so he believed the recent regression was in general code rather than the emulator. Once he saw it was emulated, he reviewed the recent changes in the emulator code to find and fix the problem.

**Comment by kmm2** [comment]
Thanks for the clarifications.

**Comment by stsp** [comment]
```
$ dpkg-query -L qemu-kvm
/.
/usr
/usr/bin
/usr/bin/kvm
/usr/share
/usr/share/doc
/usr/share/doc/qemu-kvm
/usr/share/doc/qemu-kvm/NEWS.Debian.gz
/usr/share/doc/qemu-kvm/copyright
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/kvm.1.gz
/usr/bin/kvm-spice
/usr/bin/qemu-system-x86_64-spice
/usr/share/doc/qemu-kvm/changelog.Debian.gz
```

It doesn't seem to setup any module.
Are you sure we need this?

**Comment by stsp** [comment]
```
This package provides just a wrapper
 script /usr/bin/kvm which run qemu-system-x86 in kvm mode for backwards
 compatibility.
```
Doesn't look like something to add a dep for.

**Comment by andrewbird** [comment]
> Doesn't look like something to add a dep for.

Then I guess you'll need to figure out what mechanism creates the kvm group, arranges kvm module loading and sets the device file permissions, instead?

**Comment by stsp** [comment]
Maybe some other, dependent package does
all this? I just read the package description, and
it basically says that this package is obsolete.

**Comment by andrewbird** [comment]
Seems like it's qemu-system-common that creates the group on install (we could do this)

#### /var/lib/dpkg/info/qemu-system-common.preinst
~~~
#!/bin/sh                                                                       
                                                                                
set -e                                                                          
                                                                                
case "$1" in                                                                    
install|upgrade)                                                                
    # Add the kvm group unless it's already there                               
    if ! getent group kvm >/dev/null; then                                      
        addgroup --quiet --system kvm || true                                   
    fi                                                                          
esac                                                                            
~~~

But it also has a packaged udev rule to create the device node (not sure if we should duplicate this?)
#### /lib/udev/rules.d/60-qemu-system-common.rules
~~~
KERNEL=="kvm", GROUP="kvm", MODE="0660"
~~~

(systemd used to do this too but they dropped it in https://github.com/endlessm/systemd/commit/8e7e8e42554cb27caf8f06fd0733c5b18bc0347a)

**Comment by stsp** [comment]
Thanks!

Duplicating this, will likely cause a conflict.
So... depending on qemu-system-common?
How silly... :(

@skitt can you suggest something here?
Why in 21 century packaging is still the
hardest part of the deal...

**Comment by stsp** [comment]
In https://github.com/systemd/systemd/issues/6360#issuecomment-315100346
and below, @poettering clearly said that
kvm should stay in udev.
Unfortunately he was ignored.
I pinged that discussion.
Maybe they'll reconsider, 3 years
have passed, things can change.

**Comment by stsp** [comment]
That appears to have been fixed
in systemd-240, that is available
since ubuntu eoan.
I think there is no other choice but
to depend on newer systemd and
drop the support of anything before
eoan (and in fact, of anything before
focal, because of libslirp).

Will people suffer too much from
such changes?

**Comment by stsp** [comment]
And we would still need to ask the
user to add himself into a kvm group.

**Comment by stsp** [comment]
Or maybe not, as their log says:
`Make /dev/kvm accessible to local users and group kvm.`
So it seems local users won't have to
add themselves to kvm group any more,
which is cool.
Not sure how exactly they did that though.

**Comment by skitt** [comment]
> So it seems local users won't have to
> add themselves to kvm group any more,
> which is cool.
> Not sure how exactly they did that though.

This relies on the `uaccess` mechanism: the currently-active session on each seat gets access to sound devices, the DRM device, KVM, smartcard readers, etc.

**Comment by stsp** [comment]
Thanks.
According to stackoverflow, that
works by systemd-logind assigning
an acl to the device nodes on local
logins.

**Comment by stsp** [comment]
I added the deps on systemd-udev-234
for fedora, and udev-240 for ubuntu.
Of course no compile- or run-time checks
were added, so ppl are still on their own
building dosemu2 for old systems.
It just seems that I can't support them. :(

**Comment by andrewbird** [comment]
> It just seems that I can't support them. :(

It's still better than before as at least kvm will just work for newer systems (not via ssh login though) and older systems have the same option as now to install qemu-system-common and add themselves into the kvm group.

I'm thinking that I should change travis test to just `chmod 666 /dev/kvm` and forget about the group / relogin thing. (this is what Bart suggested back in #1030)

**Comment by stsp** [comment]
> It's still better than before

Mind you, it also means no 32bit support
(focal and on are 64bit-only distros).

> older systems have the same option as now to install qemu-system-common and

... and build dosemu2 from git by hands. :(

> this is what Bart suggested

Or just add acl, as Bart also suggested. :)
As this what presumably systemd-logind
does.

**Comment by andrewbird** [comment]
> ... and build dosemu2 from git by hands. :(

I was assuming that PPA still has builds for 16.04 / 18.04 LTS ? If not it is it possible to make a distro version specific control file?

> Or just add acl, as Bart also suggested. :)

Yep, seems nicer.

**Comment by stsp** [comment]
> is it possible to make a distro version specific control file?

Creating such file is possible, but
how to use it on LP, is unclear.
Say, I could create a new git repo
on github, "dosemu-legacy", put
the old control file there and pull
in dosemu2 sources as a git submodule.
But then, LP doesn't support git
submodules...

**Comment by andrewbird** [comment]
Actually, do you need to add dependencies on those udev versions, it's good that we know at what version things just work, but I doubt it actually causes anything to be installed over and above the base system?

**Comment by stsp** [comment]
Protects from installing new packages
on an old systems. :)
Not sure, really.
I had the following considerations in mind:
1. kvm-less DPMI is currently insecure, so
there is no need to provide such packages
officially. They can be provided as "dosemu-legacy",
in which case their security doesn't matter.
2. users can have slower performance because
vm86-jit instead of kvm, and will complain/drop
dosemu2.
3. w/o libslirp we also have pretty much nothing
to offer on a networking front
4. degraded localization (json-c problem)

So overall I thought providing the packages
for old systems should really be cleanly
separated. They should have the different
name ("dosemu-legacy"). But its unclear
if we can build them from the same sources,
or we can't. If we can, no one would be
seriously hurt, so I view such a way as a
good one.

**Comment by stsp** [comment]
OK, I know what can be done.
We can create the legacy branch
in git and change the control there.
Then create another recipe (and
another project) at LP, which will
build from that branch and put to
our usual PPA.
Do you want to do that? :)

**Comment by andrewbird** [comment]
But that means you have to rebase or merge with devel all the time to keep in sync. Maybe you should just create them by hand for tagged releases?

**Comment by stsp** [comment]
Yes, but this legacy branch will only
have 1 extra patch, so merging should
always be trivial.
Its basically the same as creating it by
hands, just a more automated way.
You can write script that will mangle
the control file and create an additional
branch automatically. It will work except
at LP you'll always have to fix up the
branch name, if the script is going to
create the new one. Or you can always
re-create the branch with the same name.
This is what you propose.

Keeping the single patch in a different
branch and merging devel there with
script, will only allow to have the smaller
script - i.e. git will replace the sed machinery
here.
I can't think of any other differences
actually.

**Comment by stsp** [comment]
I created the dosemu2-legacy recipe:
https://code.launchpad.net/~stsp-0/+recipe/dosemu2-legacy
Unfortunately I also created the project with the same name:
https://launchpad.net/dosemu2-legacy
and don't know how to delete it.
