### ISSUE TITLE
Visual Player hangs on startup

### ISSUE THREAD

**Issue by volkertb** [dosemu2/dosemu2#1317]
**Describe the bug**
Visual Player, the DOS MOD player, hangs in Dosemu2 on startup. I tested this with the shareware distribution of version 2.0 of the application, released in March '93.

**To Reproduce**
Steps to reproduce the behaviour:

**Attach program/game binaries or provide an URL**
The shareware distribution (same one I tried) can be downloaded from https://vetusware.com/download/Visual%20Player%202.0/?id=9422 (free registration required)

**Attach the log**
I used the command `dosemu -D+9Sqv`, to log video, sound and DMA. I assumed that the plus sign and the 9 would mean "most verbose" or something. Please let me know if I did this wrong.

Here is the output from `~/.dosemu/boot.log`, after the application hung and I closed the dosemu2 window.

[boot.log](https://github.com/dosemu2/dosemu2/files/5388315/boot.log)

**Note**: when I ran the same command, but with `-O` to log to the console, I noticed that the last printed log line when the application hung was `SB: Output fillup incomplete (0 0 1)`.

**A regression?**
Haven't tried it with Dosemu1. The application works with DOSBox, though.

**Additional info**
It's a real mode application, I unzipped the archive and ran vp.exe and it just hang.

See also the screenshot:

![Screenshot from 2020-10-16 00-52-36](https://user-images.githubusercontent.com/518023/96195022-fad29280-0f4b-11eb-8dd6-3825858c3194.png)

**Comment by stsp** [comment]
-D9+xxx
Can you also check with ms-dos to make
sure its not an fdpp problem?

**Comment by andrewbird** [comment]
No space on `c:` drive perhaps?

**Comment by volkertb** [comment]
> No space on `c:` drive perhaps?

@andrewbird Heh, I just did `dir` in dosemu2 and it's showing `0 byte(s) free`. (I assume this was done by dosemu2 deliberaty for compatibility and/or performance reasons?) It still allows me to create files, and the partition on which I have `~/.dosemu/drive_c` has more than enough space for DOS stuff. So I don't see how this issue could be caused by a possible lack of available disk space on the C: drive of the VM.

@stsp I also tried it with qemu-kvm (running FreeDOS in the VM) and with DOSBox. In DOSBox the application worked, in FreeDOS under qemu-kvm, the application would show a black screen, although I could still exit the application to DOS by pressing the Esc key. Audio for this application doesn't work under qemu-kvm. (I tested that by making the player play a MOD file from the command line.) I tried both the SB16 emulation and the cs4231a emulation.

I just tried it in dosemu2 again with the `-D9+xxx` logging parameter as you suggested. Here's the resulting log:

[boot.log](https://github.com/dosemu2/dosemu2/files/5394711/boot.log)

**Comment by andrewbird** [comment]
> Heh, I just did dir in dosemu2 and it's showing 0 byte(s) free. (I assume this was done by dosemu2 deliberately for compatibility and/or performance reasons?)

I only noticed it on your screenshot, so I have no special insight into your issue. As you say if you can create files etc, then I agree it's doubtful that's your problem. Still it's curious to me as I've only ever seen either the right free space value or one that's clamped at 2GB.

**Comment by stsp** [comment]
Yes, I confirm "0 byte(s) free" reporting.
I filled a bug about that.

**Comment by stsp** [comment]
Download of VP is available only to
registered members. Can you upload it?

**Comment by volkertb** [comment]
Of course. It's shareware, after all. :wink:

Here's the ZIP archive:

[vp.zip](https://github.com/dosemu2/dosemu2/files/5396185/vp.zip)

**Comment by stsp** [comment]
Yes, for me it draws 1-2 buttons, then hangs.

**Comment by volkertb** [comment]
OK. It's weird how it hangs differently on your machine than it does on mine. I just retried it with dosemu2 revision 5387, and it still hangs like in the screenshot I shared earlier, i.e. with a blinking cursor below the entered command.

Do you have dosemu2 configured differently than I do? I don't remember changing anything in the default configuration from when I installed it.

**Comment by stsp** [comment]
Yes, for me the hang is not even
complete: it still reacts on Esc for
example, so I can exit.
Btw, 0 byte(s) free should now be
fixed.

**Comment by volkertb** [comment]
`VP.EXE` still hanging on startup as of the following dosemu2 version:

```
$ dosemu --version
dosemu2-2.0pre8-20200328-1688-g3bcd15ef
Revision: 5387
```

**Comment by andrewbird** [comment]
> dosemu2-2.0pre8-20200328-1688-g3bcd15ef
Revision: 5387

Mine from the Ubuntu PPA is revision 6157.

The git ref there appears to be really old.
~~~
commit 3bcd15efd989b429b964a2eaa9259e461ed9cb56
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sat Mar 28 18:04:06 2020 +0300

    Some doc updates [#1070]
    
    Update man for -kr and remove outdated README.plugins.
~~~

**Comment by volkertb** [comment]
Ah, my bad! :sweat_smile:

The machine on which I tried this is running Fedora 34, with the `Copr repo for dosemu2 owned by stsp` repository enabled. And yes, it was regularly receiving new builds of dosemu2.

However, it turns out that I still had an old, locally compiled build of dosemu2 installed in `/usr/local/bin`, which of course takes precedence over `/usr/bin`.

Sorry for the confusion!

Anyway, I got rid of the old dosemu2 installation in `/usr/local` and retried `vp.exe`.

It no longer hangs. Instead, dosemu2 crashes with the following error:

```
ERROR: general protection at 0x7f504097b3d8: ad
```

This happened with the following version/build of `dosemu2`:

```
$ dosemu --version
dosemu2-2.0pre8
Revision: 6157
```

**Comment by stsp** [comment]
This has something to do with
relocating fdpp to UMB.
The work-around would be needed,
but since vp didn't work also before,
I don't see a need to change anything.
Of course we need to be careful
to not miss some other prog that
breaks when DOS is in UMB but
otherwise worked fine.
