### ISSUE TITLE
The BIOS timer tick dword at [46Ch] starts at 0 when starting dosemu

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1385]
**Describe the bug**
The timer tick should indicate the time of day (wall clock time). Actual behaviour is the timer tick starts counting at zero, making it appear like the time of day is just past midnight regardless of the actual time of day.

**To Reproduce**
In the lclock repo directory, use the following command:

`./mak.sh && dosemu -K "$PWD" -T -E "lclock"`

(Must have lmacros files in the same directory or in the ../lmacros/ directory.)

Tested on "Build 2.0pre8-20210107-2657-gd9079b724".

**Attach program/game binaries or provide an URL**
https://hg.ulukai.org/ecm/lclock/ + https://hg.ulukai.org/ecm/lmacros/

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/5781671/boot.log)

**Additional info**
Using FreeDOS kernel 2042.

**Comment by stsp** [comment]
Not sure, DOS initializes them on start.
But I added the extra initialization.

**Comment by ecm-pushbx** [comment]
Doesn't work. Still says midnight.

**Comment by ecm-pushbx** [comment]
The DOS `time` command also says 12:00am

**Comment by stsp** [comment]
`dosemu -H1`
in another terminal:
`dosdebug`
```
dosdebug> d 40:6c

0040:006c 73 4B 12 00 00 00 00 00 00 06 00 00 14 14 14 00  sK..............
0040:007c 00 00 00 00 1E 00 3E 00 18 00 00 60 F9 51 08 00  ......>....`yQ..
0040:008c 00 00 00 00 00 00 00 00 00 00 10 00 00 00 00 00  ................
0040:009c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0040:00ac 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0040:00bc 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0040:00cc 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0040:00dc 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................

dosdebug> kill
```

So it works!

**Comment by stsp** [comment]
```
J: HD6, Pri[ 1], CHS=    0-1-1, start=     0 MB, size=   255 MB
SWITCHES=#0[Y,N]?N
Process 0 starting: I:\command.com /D /P /E:256
C:\>time
Current time is  7:19:19.00p
C:\> 
```

**Comment by stsp** [comment]
Not sure what else to check.

**Comment by ecm-pushbx** [comment]
That works for me too:

```
~/.dosemu/run$ ~/local.new/bin/dosdebug

DOSEMU Debugger V0.6 connected
- type ? to get help on commands -
system state: emulated,stopped
AX=0000  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=00133202
CS:IP=ff10:020b       SS:SP=0000:fffe

ff10:020b F4               hlt

system state: emulated,stopped
AX=0000  BX=0000  CX=0000  DX=0000  SI=0000  DI=0000  SP=fffe  BP=0000
DS=0040  ES=0000  FS=0000  GS=0000  FL=00133202
CS:IP=ff10:020b       SS:SP=0000:fffe

ff10:020b F4               hlt

dosdebug> d 40:6C

0040:006c D1 5E 11 00
```

**Comment by ecm-pushbx** [comment]
When I run the machine with `g` then somehow the tick count is reset so it is close to zero again.

**Comment by stsp** [comment]
What is `g`?

**Comment by ecm-pushbx** [comment]
`G` command to `dosdebug`

**Comment by ecm-pushbx** [comment]
If I place `ldebug.com` as `kernel.sys` and boot into the FreeDOS kernel then at first (in lDebug command line) the ticks are fine, but at some point they are reset when booting FreeDOS. I don't know why yet.

**Comment by ecm-pushbx** [comment]
Commands used:

```
boot protocol freedos fdkernel.sys
r v0 = dword [0:0]
tp ff_ffff while v0 == dword [0:0] && dword [0:46C] > 11_0000 silent
```

At this point you need to step and skip instructions a little so that the debugger's interrupt 1, 3, 6 handlers are not overwritten by the kernel. Then:

```
tp ff_ffff while dword [0:46C] > 11_0000 silent
```

I don't know what to make of this though. The instructions shown in the silent dump do not appear to be why the tick count is reset.

```
AX=2D00 BX=233A CX=1124 DX=3400 SP=2354 BP=2360 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=43A8 NV UP EI PL NZ NA PO NC
8389:43A8 C3                retn
AX=2D00 BX=233A CX=1124 DX=3400 SP=2356 BP=2360 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=07C1 NV UP EI PL NZ NA PO NC
8389:07C1 C41E5A01          les     bx, [015A]                DS:015A=00D9:0000
AX=2D00 BX=0000 CX=1124 DX=3400 SP=2356 BP=2360 SI=FFFE DI=FFFE
DS=87C8 ES=00D9 SS=87C8 CS=8389 IP=07C5 NV UP EI PL NZ NA PO NC
8389:07C5 26C647471A        mov     byte [es:bx+47], 1A              ES:0047=00
AX=2D00 BX=0000 CX=1124 DX=3400 SP=2356 BP=2360 SI=FFFE DI=FFFE
DS=87C8 ES=00D9 SS=87C8 CS=8389 IP=07CA NV UP EI PL NZ NA PO NC
8389:07CA E80F3B            call    42DC
AX=2D00 BX=0000 CX=1124 DX=3400 SP=2354 BP=2360 SI=FFFE DI=FFFE
DS=87C8 ES=00D9 SS=87C8 CS=8389 IP=42DC NV UP EI PL NZ NA PO NC
8389:42DC 683D0F            push    word 0F3D
AX=2D00 BX=0000 CX=1124 DX=3400 SP=2352 BP=2360 SI=FFFE DI=FFFE
DS=87C8 ES=00D9 SS=87C8 CS=8389 IP=42DF NV UP EI PL NZ NA PO NC
8389:42DF E835EF            call    3217
AX=2D00 BX=0000 CX=1124 DX=3400 SP=2350 BP=2360 SI=FFFE DI=FFFE
DS=87C8 ES=00D9 SS=87C8 CS=8389 IP=3217 NV UP EI PL NZ NA PO NC
8389:3217 C8020000          enter   0002, 00
AX=2D00 BX=0000 CX=1124 DX=3400 SP=234C BP=234E SI=FFFE DI=FFFE
DS=87C8 ES=00D9 SS=87C8 CS=8389 IP=321B NV UP EI PL NZ NA PO NC
8389:321B 8D4606            lea     ax, [bp+06]
AX=2354 BX=0000 CX=1124 DX=3400 SP=234C BP=234E SI=FFFE DI=FFFE
DS=87C8 ES=00D9 SS=87C8 CS=8389 IP=321E NV UP EI PL NZ NA PO NC
8389:321E 8946FE            mov     [bp-02], ax                    SS:234C=3302
AX=2354 BX=0000 CX=1124 DX=3400 SP=234C BP=234E SI=FFFE DI=FFFE
DS=87C8 ES=00D9 SS=87C8 CS=8389 IP=3221 NV UP EI PL NZ NA PO NC
8389:3221 C706180B0000      mov     word [0B18], 0000              DS:0B18=0000
AX=2354 BX=0000 CX=1124 DX=3400 SP=234C BP=234E SI=FFFE DI=FFFE
DS=87C8 ES=00D9 SS=87C8 CS=8389 IP=3227 NV UP EI PL NZ NA PO NC
8389:3227 FF7604            push    word [bp+04]                   SS:2352=0F3D
AX=2354 BX=0000 CX=1124 DX=3400 SP=234A BP=234E SI=FFFE DI=FFFE
DS=87C8 ES=00D9 SS=87C8 CS=8389 IP=322A NV UP EI PL NZ NA PO NC
8389:322A 50                push    ax
AX=2354 BX=0000 CX=1124 DX=3400 SP=2348 BP=234E SI=FFFE DI=FFFE
DS=87C8 ES=00D9 SS=87C8 CS=8389 IP=322B NV UP EI PL NZ NA PO NC
8389:322B E82600            call    3254
While condition "dword [0:46C] > 11_0000" no longer true.
-dd 0:46c l4
header     0        4        8        C        0123456789ABCDEF
0000:0460                   -         0000017C             |...
-
```

**Comment by ecm-pushbx** [comment]
Here's the entire log of a run with `-dumb`: https://ulukai.org/ecm/test/20210107.txt -- as before, kernel.sys = ldebug.com and fdkernel.sys = FreeDOS kernel 2042. (This would not display the clock drawn into the text mode buffer by the TSR, but the tick count appears to be set and reset the same way as without `-dumb` / with `-t`.)

**Comment by ecm-pushbx** [comment]
Final output from the linked log file:

```
-tp ff_ffff while dword [0:46C] > 11_0000 && dword [0:46C] < 14_0000 silent
FreeDOS kernel - SVN (build 2042 OEM:0xfd) [compiled Jan 24 2020]
Kernel compatibility 7.10 - BORLANDC - 80386 CPU required - FAT32 support

(C) Copyright 1995-2012 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
AX=0001 BX=0001 CX=2021 DX=0001 SP=233A BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=435A NV UP EI PL NZ NA PO NC
8389:435A 8846EF            mov     [bp-11], al                      SS:2341=03
AX=0001 BX=0001 CX=2021 DX=0001 SP=233A BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=435D NV UP EI PL NZ NA PO NC
8389:435D A0680F            mov     al, [0F68]                       DS:0F68=07
AX=0007 BX=0001 CX=2021 DX=0001 SP=233A BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=4360 NV UP EI PL NZ NA PO NC
8389:4360 B400              mov     ah, 00
AX=0007 BX=0001 CX=2021 DX=0001 SP=233A BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=4362 NV UP EI PL NZ NA PO NC
8389:4362 50                push    ax
AX=0007 BX=0001 CX=2021 DX=0001 SP=2338 BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=4363 NV UP EI PL NZ NA PO NC
8389:4363 E889FF            call    42EF
AX=0007 BX=0001 CX=2021 DX=0001 SP=2336 BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=42EF NV UP EI PL NZ NA PO NC
8389:42EF 55                push    bp
AX=0007 BX=0001 CX=2021 DX=0001 SP=2334 BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=42F0 NV UP EI PL NZ NA PO NC
8389:42F0 8BEC              mov     bp, sp
AX=0007 BX=0001 CX=2021 DX=0001 SP=2334 BP=2334 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=42F2 NV UP EI PL NZ NA PO NC
8389:42F2 8B5E04            mov     bx, [bp+04]                    SS:2338=0007
AX=0007 BX=0007 CX=2021 DX=0001 SP=2334 BP=2334 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=42F5 NV UP EI PL NZ NA PO NC
8389:42F5 8BC3              mov     ax, bx
AX=0007 BX=0007 CX=2021 DX=0001 SP=2334 BP=2334 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=42F7 NV UP EI PL NZ NA PO NC
8389:42F7 C1F804            sar     ax, 04
AX=0000 BX=0007 CX=2021 DX=0001 SP=2334 BP=2334 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=42FA NV UP EI PL ZR NA PE NC
8389:42FA 250F00            and     ax, 000F
AX=0000 BX=0007 CX=2021 DX=0001 SP=2334 BP=2334 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=42FD NV UP EI PL ZR NA PE NC
8389:42FD 6BC00A            imul    ax, ax, +0A
AX=0000 BX=0007 CX=2021 DX=0001 SP=2334 BP=2334 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=4300 NV UP EI PL NZ NA PE NC
8389:4300 8BD3              mov     dx, bx
AX=0000 BX=0007 CX=2021 DX=0007 SP=2334 BP=2334 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=4302 NV UP EI PL NZ NA PE NC
8389:4302 83E20F            and     dx, +0F
AX=0000 BX=0007 CX=2021 DX=0007 SP=2334 BP=2334 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=4305 NV UP EI PL NZ NA PO NC
8389:4305 03C2              add     ax, dx
AX=0007 BX=0007 CX=2021 DX=0007 SP=2334 BP=2334 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=4307 NV UP EI PL NZ NA PO NC
8389:4307 5D                pop     bp
AX=0007 BX=0007 CX=2021 DX=0007 SP=2336 BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=4308 NV UP EI PL NZ NA PO NC
8389:4308 C20200            retn    0002
AX=0007 BX=0007 CX=2021 DX=0007 SP=233A BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=4366 NV UP EI PL NZ NA PO NC
8389:4366 8846EE            mov     [bp-12], al                      SS:2340=B2
AX=0007 BX=0007 CX=2021 DX=0007 SP=233A BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=4369 NV UP EI PL NZ NA PO NC
8389:4369 6A21              push    +21
AX=0007 BX=0007 CX=2021 DX=0007 SP=2338 BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=436B NV UP EI PL NZ NA PO NC
8389:436B 8D46E8            lea     ax, [bp-18]
AX=233A BX=0007 CX=2021 DX=0007 SP=2338 BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=436E NV UP EI PL NZ NA PO NC
8389:436E 50                push    ax
AX=233A BX=0007 CX=2021 DX=0007 SP=2336 BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=436F NV UP EI PL NZ NA PO NC
8389:436F E862BE            call    01D4
AX=233A BX=0007 CX=2021 DX=0007 SP=2334 BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01D4 NV UP EI PL NZ NA PO NC
8389:01D4 55                push    bp
AX=233A BX=0007 CX=2021 DX=0007 SP=2332 BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01D5 NV UP EI PL NZ NA PO NC
8389:01D5 89E5              mov     bp, sp
AX=233A BX=0007 CX=2021 DX=0007 SP=2332 BP=2332 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01D7 NV UP EI PL NZ NA PO NC
8389:01D7 56                push    si
AX=233A BX=0007 CX=2021 DX=0007 SP=2330 BP=2332 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01D8 NV UP EI PL NZ NA PO NC
8389:01D8 57                push    di
AX=233A BX=0007 CX=2021 DX=0007 SP=232E BP=2332 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01D9 NV UP EI PL NZ NA PO NC
8389:01D9 1E                push    ds
AX=233A BX=0007 CX=2021 DX=0007 SP=232C BP=2332 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01DA NV UP EI PL NZ NA PO NC
8389:01DA 8B4606            mov     ax, [bp+06]                    SS:2338=0021
AX=0021 BX=0007 CX=2021 DX=0007 SP=232C BP=2332 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01DD NV UP EI PL NZ NA PO NC
8389:01DD 2EA20202          mov     [cs:0202], al                    CS:0202=1A
AX=0021 BX=0007 CX=2021 DX=0007 SP=232C BP=2332 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01E1 NV UP EI PL NZ NA PO NC
8389:01E1 EB00              jmp     01E3
AX=0021 BX=0007 CX=2021 DX=0007 SP=232C BP=2332 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01E3 NV UP EI PL NZ NA PO NC
8389:01E3 8B5E04            mov     bx, [bp+04]                    SS:2336=233A
AX=0021 BX=233A CX=2021 DX=0007 SP=232C BP=2332 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01E6 NV UP EI PL NZ NA PO NC
8389:01E6 8B07              mov     ax, [bx]                       DS:233A=2B89
AX=2B89 BX=233A CX=2021 DX=0007 SP=232C BP=2332 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01E8 NV UP EI PL NZ NA PO NC
8389:01E8 8B4F04            mov     cx, [bx+04]                    DS:233E=07E5
AX=2B89 BX=233A CX=07E5 DX=0007 SP=232C BP=2332 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01EB NV UP EI PL NZ NA PO NC
8389:01EB 8B5706            mov     dx, [bx+06]                    DS:2340=0107
AX=2B89 BX=233A CX=07E5 DX=0107 SP=232C BP=2332 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01EE NV UP EI PL NZ NA PO NC
8389:01EE 8B7708            mov     si, [bx+08]                    DS:2342=065E
AX=2B89 BX=233A CX=07E5 DX=0107 SP=232C BP=2332 SI=065E DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01F1 NV UP EI PL NZ NA PO NC
8389:01F1 8B7F0A            mov     di, [bx+0A]                    DS:2344=0000
AX=2B89 BX=233A CX=07E5 DX=0107 SP=232C BP=2332 SI=065E DI=0000
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01F4 NV UP EI PL NZ NA PO NC
8389:01F4 8B6F0C            mov     bp, [bx+0C]                    DS:2346=8389
AX=2B89 BX=233A CX=07E5 DX=0107 SP=232C BP=8389 SI=065E DI=0000
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01F7 NV UP EI PL NZ NA PO NC
8389:01F7 FF770E            push    word [bx+0E]                   DS:2348=430B
AX=2B89 BX=233A CX=07E5 DX=0107 SP=232A BP=8389 SI=065E DI=0000
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01FA NV UP EI PL NZ NA PO NC
8389:01FA 8E4710            mov     es, word [bx+10]               DS:234A=0000
AX=2B89 BX=233A CX=07E5 DX=0107 SP=232A BP=8389 SI=065E DI=0000
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=01FD NV UP EI PL NZ NA PO NC
8389:01FD 8B5F02            mov     bx, [bx+02]                    DS:233C=0000
AX=2B89 BX=0000 CX=07E5 DX=0107 SP=232A BP=8389 SI=065E DI=0000
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=0200 NV UP EI PL NZ NA PO NC
8389:0200 1F                pop     ds
AX=2B89 BX=0000 CX=07E5 DX=0107 SP=232C BP=8389 SI=065E DI=0000
DS=430B ES=0000 SS=87C8 CS=8389 IP=0201 NV UP EI PL NZ NA PO NC
8389:0201 CD21              int     21
AX=2B00 BX=0000 CX=07E5 DX=0107 SP=232C BP=8389 SI=065E DI=0000
DS=430B ES=0000 SS=87C8 CS=8389 IP=0203 NV UP EI PL NZ NA PO NC
8389:0203 9C                pushf
While condition "dword [0:46C] > 11_0000 && dword [0:46C] < 14_0000" no longer true.
-dd 0:46C l 4
header     0        4        8        C        0123456789ABCDEF
0000:0460                   -         00000090             ....
-
```

**Comment by stsp** [comment]
Please see into int1a code as it updates
that counter. You'll quickly find out if it is
it or not.

**Comment by ecm-pushbx** [comment]
Running `dosemu -D+h` results in this log: https://ulukai.org/ecm/test/20210107/boot.log

Filtering out the HLT lines like so `cat boot.log | grep -Ev '^HLT: ' > ~/wwwecm/test/20210107/nohlt.log` results in https://ulukai.org/ecm/test/20210107/nohlt.log which ends as follows:

```
TIME: using 9154 usec for updating ALRM timer
======================= ENTER CPU-EMU ===============

CONF: freeing region for 'E' (EMS page frame)
config.boot_dos set to 10000
config.int_hooks set to -1
config.force_revect set to 0
TICKS: update ticks to 1211301
TICKS: update ticks to 1211301
```

This is the expected value for a time around 18:20. However, next there is:

```
TICKS: update ticks to 2074345490
TICKS: update ticks to 0
TICKS: update ticks to 2074017810
TICKS: update ticks to 1
TICKS: update ticks to 1
TICKS: update ticks to 2
TICKS: update ticks to 2
TICKS: update ticks to 6
TICKS: update ticks to 6
TICKS: update ticks to 7
TICKS: update ticks to 7
TICKS: update ticks to 7
TICKS: update ticks to 8
TICKS: update ticks to 8
TICKS: update ticks to 8
TICKS: update ticks to 8
TICKS: update ticks to 8
TICKS: update ticks to 8
CONF: reserving 124Kb at 0xC1000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 48Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
TICKS: update ticks to 8
TICKS: update ticks to 8
TICKS: update ticks to 8
TICKS: update ticks to 8
TICKS: update ticks to 8
TICKS: update ticks to 8
TICKS: update ticks to 8
TICKS: update ticks to 8
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
TICKS: update ticks to 9
RTC: cmos update 18:28:52, B=0x2
8042: read port 0x60 = 0x14
8042: read port 0x60 = 0x94
RTC: cmos update 18:28:53, B=0x2
8042: read port 0x60 = 0x17
8042: read port 0x60 = 0x97
8042: read port 0x60 = 0x32
8042: read port 0x60 = 0xb2
8042: read port 0x60 = 0x12
8042: read port 0x60 = 0x92
8042: read port 0x60 = 0x1c
8042: read port 0x60 = 0x9c
TICKS: update ticks to 48
RTC: cmos update 18:28:54, B=0x2
RTC: cmos update 18:28:55, B=0x2
8042: read port 0x60 = 0x1c
8042: read port 0x60 = 0x9c
8042: read port 0x60 = 0x12
8042: read port 0x60 = 0x92
8042: read port 0x60 = 0x2d
8042: read port 0x60 = 0xad
8042: read port 0x60 = 0x17
8042: read port 0x60 = 0x97
RTC: cmos update 18:28:56, B=0x2
8042: read port 0x60 = 0x14
8042: read port 0x60 = 0x94
8042: read port 0x60 = 0x12
8042: read port 0x60 = 0x92
8042: read port 0x60 = 0x32
8042: read port 0x60 = 0xb2
8042: read port 0x60 = 0x16
8042: read port 0x60 = 0x96
RTC: cmos update 18:28:57, B=0x2
8042: read port 0x60 = 0x1c
8042: read port 0x60 = 0x9c
DOS termination requested
leavedos(do_doshelper:64|0) called - shutting down
leavedos thread started
leavedos thread ended
coopthreads stopped
======================= LEAVE CPU-EMU ===============


Package info:
```

**Comment by ecm-pushbx** [comment]
This is the spot that displays the `update ticks to` message: https://github.com/dosemu2/dosemu2/blob/6018806ac4d08cf0518ee6d3b6ff658218709591/src/base/core/int.c#L1070

**Comment by stsp** [comment]
Please find out who calls it with the
wrong value. There are not too many callers.

**Comment by ecm-pushbx** [comment]
I think FreeDOS calls down to Int1A in https://github.com/FDOS/kernel/blob/92ae538f1d89a3d90ab7c44a5c61f5f0c8070eec/kernel/sysclk.c#L103-L126

and this is called by interrupt 21h service 2Bh (set date) in https://github.com/FDOS/kernel/blob/92ae538f1d89a3d90ab7c44a5c61f5f0c8070eec/kernel/systime.c#L155-L172

I'm not sure yet how it gets the wrong time values. I assume the C_INPUT call is supposed to populate valid time values into the structure.

**Comment by stsp** [comment]
dosemu2's int1a handler updates the
time even when _reading_ only.
So you don't need to mess with freedos.
See if maybe dosemu2 itself provides
the bad values on read.

**Comment by ecm-pushbx** [comment]
No it is FreeDOS, it is this bug: https://github.com/FDOS/kernel/commit/ef945b11929d9be781dfd8bb042a0fa1d5fcde02

**Comment by ecm-pushbx** [comment]
Fixed 2020 Aug 21.

**Comment by stsp** [comment]
Have never seen such bug in fdpp.
Why you are still not using fdpp?
It has your long-seek extensions.

**Comment by ecm-pushbx** [comment]
I'd rather keep using FreeDOS kernel. It is easier to debug for me.

I fixed the issue using a hex editor, now lClock works in the most recent as well as older dosemu. The kernel file is the one Andrew or you provided in some thread:

```
dosemu/drive_c$ md5sum kernel.sys.new
3f4df972ae34f9d3a884bfd12b317516  kernel.sys.new
.dosemu/drive_c$ bdiff kernel.sys.pat kernel.sys.new
File: kernel.sys.pat
00D443: 5A 59   [ 59 5A ]
.dosemu/drive_c$ 
```

The search string in the uncompressed kernel.sys is `C3 58 59 5A 50 B4 01 CD 1A C3`.

However, turns out that your patch here is needed to get the correct tick count in boot-loaded lDebug: (with ldebug.com as kernel.sys)

```
lclock$ ./mak.sh && dosemu -K "$PWD" -T -E lclock -dumb
ERROR: alsa_midi (ALSA lib): seq_hw.c:466:(snd_seq_hw_open) : No such file or direc
tory open /dev/snd/seq failed
dosemu2 2.0pre8-20190609-1074-g8596bd5b
Configured: 2019-06-09 20:56:57 +0200
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org


-h dword [0:46C]
00ED  decimal: 237
-boot quit
lclock$ ./mak.sh && ~/local.new/bin/dosemu -K "$PWD" -T -E lclock -dumb
Compatibility warning: found deprecated setup of dosemu2 pre-alpha version.
    If you do not intend to run such old dosemu2 versions
    (dosemu1 is fine), please do:
        rm ~/.dosemu/drives/*.lnk
    You may also do
        rm -rf ~/.dosemu/drives
    if you dont intend to run dosemu1.
ERROR: KVM: error opening /dev/kvm: No such file or directory
ERROR: alsa_midi (ALSA lib): seq_hw.c:466:(snd_seq_hw_open) : No such file or direc
tory open /dev/snd/seq failed
ERROR: Unable to open console or check with X to evaluate the keyboard map.
Please specify your keyboard map explicitly via the $_layout option. Defaulting to
US.
dosemu2 2.0pre8-20210107-2658-g6018806ac Configured: 2021-01-07 16:52:27 +0100
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/dosemu2/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, GPL v2 (or any later version) distribution conditions.


-h dword [0:46C]
0013C3EE  decimal: 1295342
-boot quit
lclock$
```

**Comment by stsp** [comment]
> It is easier to debug for me.

With your debugger - yes.
And with gdb? :)

> However, turns out that your patch here is needed to get the correct tick count in boot

Yes, I verified with dosdebug that there
is a problem, and only then applied the patch.

**Comment by ecm-pushbx** [comment]
I don't know how to use gdb to debug fdpp.

**Comment by stsp** [comment]
```
$ gdb dosemu.bin
Reading symbols from dosemu.bin...
(gdb) b FreeDOSmain
Function "FreeDOSmain" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (FreeDOSmain) pending.
(gdb) r
Starting program: /usr/local/bin/dosemu.bin
Thread 1 "dosemu.bin" hit Breakpoint 1, FreeDOSmain () at main.cc:82
```

Its that simple!

**Comment by stsp** [comment]
In fdpp build dir it is recommended to
put the file local.mak that has `EXTRA_DEBUG = 1`
line. Then the debugging will be much
better than without.
Additionally you can do `dosemu -D9+f`
to get the fdpp log messages in the dosemu
log.
There is never a more comfortable debugging
than that.

**Comment by stsp** [comment]
`DEBUG_MSGS=1` is also helpful.

**Comment by ecm-pushbx** [comment]
Remark: The odd result in https://github.com/dosemu2/dosemu2/issues/1385#issuecomment-756235192 is probably because FreeDOS set a large value, and it took several (dozen) instructions until the ROM-BIOS interrupt 08h handler came along and tried to increment the tick count. Only then did it reset to zero and the condition became untrue.

**Comment by ecm-pushbx** [comment]
I may look into debugging fdpp more at a later time. Thanks for the pointers.

**Comment by andrewbird** [comment]
BTW, that ldebug conditional trace looked really powerful!

```
tp ff_ffff while dword [0:46C] > 11_0000 && dword [0:46C] < 14_0000 silent
FreeDOS kernel - SVN (build 2042 OEM:0xfd) [compiled Jan 24 2020]
Kernel compatibility 7.10 - BORLANDC - 80386 CPU required - FAT32 support

(C) Copyright 1995-2012 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
AX=0001 BX=0001 CX=2021 DX=0001 SP=233A BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=435A NV UP EI PL NZ NA PO NC
8389:435A 8846EF            mov     [bp-11], al                      SS:2341=03
AX=0001 BX=0001 CX=2021 DX=0001 SP=233A BP=2352 SI=FFFE DI=FFFE
DS=87C8 ES=0000 SS=87C8 CS=8389 IP=435D NV UP EI PL NZ NA PO NC

<snip>

8389:0201 CD21              int     21
AX=2B00 BX=0000 CX=07E5 DX=0107 SP=232C BP=8389 SI=065E DI=0000
DS=430B ES=0000 SS=87C8 CS=8389 IP=0203 NV UP EI PL NZ NA PO NC
8389:0203 9C                pushf
While condition "dword [0:46C] > 11_0000 && dword [0:46C] < 14_0000" no longer true.
-dd 0:46C l 4
header     0        4        8        C        0123456789ABCDEF
0000:0460                   -         00000090             ....
-

```

**Comment by ecm-pushbx** [comment]
Thanks, it does come in handy now and then. The [SBC188 FreeDOS boot bug](https://www.bttr-software.de/forum/forum_entry.php?id=16868&page=1&order=last_answer&descasc=DESC&category=all) also took all of conditional tracing, tracing into the silent buffer, and bootloading lDebug to figure out.

The silent buffer is needed to greatly speed up conditional tracing, which is greatly terminal-I/O-bound without the SILENT keyword. That keyword makes it so all trace output goes into an 8 KiB buffer that keeps cycling backwards when full. Eventually, only the most recent buffer contents are actually displayed.

**Comment by ecm-pushbx** [comment]
Oh, to mention, the SBC188 bug was dependent on the terminal output of the bootloader itself, so the silent buffer was needed to catch it too. Without the silent buffer the bug would not have reproduced in the debugger.
