### ISSUE TITLE
Locking mouse to DOSEMU2 window?

### ISSUE THREAD

**Issue by AlbertHamik** [dosemu2/dosemu2#1464]
Title explains itself, really. I'm dealing with a game that runs perfectly in DOSEMU2 so far where virtually everything else VM/Emulator related has failed, but I'm not sure how to lock the mouse to the DOSEMU2 window. I'm working from the AUR build that I installed to Manjaro.

EDIT: NVM, I didn't find the answer prior because the way it's been answered in the past was worded awkwardly. This was my answer: https://github.com/dosemu2/dosemu2/issues/1458

EDIT EDIT: Actually that's not working. I can't lock the mouse. I found the option to change what the keybind is for "[activating] mouse grab" but that is most assuredly not working either.

**Comment by stsp** [comment]
Try Ctrl-Alt-f for a full-screen.

**Comment by AlbertHamik** [comment]
I noticed that I had to unbind a thing in my WM for ctrl-alt-f to work but it does, and it allow the mouse to stay within the game window. I'm learning there could be some buginess to the default, um, DOS interface/OS(?) that DOSEMU2 is provided with. I'm also certain there's nothing bound to ctrl-alt-home or the other options I've tried to rebind to. It's weird to me the mouse hook option is not working.

**Comment by stsp** [comment]
dosemu2 have many options, and
what's used in your case, is unknown.
Try `dosemu -X` and `dosemu -S` to
check the X and SDL options separately.
Maybe in either one mode Ctrl-Alt-Home
will work.

**Comment by AlbertHamik** [comment]
dosemu -X made it where dosemu would only open in a terminal, and I don't know if one can get a graphical mode from terminal because my game crashed unable to find graphics. I assume I've been using SDL mode by default, and that won't lock the mouse at all. Also I know this is unrelated to the current issue but is dosemu2 able to mount img files for HDD, or does it have to be a directory?

**Comment by stsp** [comment]
This means that your build
is reduced. You can build it
from sources, and `dosemu -X`
won't start in a terminal.
Terminal is just a fall-back.

Of course dosemu2 is able
to mount image files.

**Comment by AlbertHamik** [comment]
okay, I'll try building it. I assume to use the repo directly for compile as the releases page hasn't been touched since 2017. And how exactly do I mount an image file? I wanted to try using my MS-DOS 7.10 image out with DOSEMU2 for testing.

**Comment by AlbertHamik** [comment]
This is what version I got from AUR by the way: 
![image](https://user-images.githubusercontent.com/1538869/116013818-2079dc00-a600-11eb-9653-12601a587065.png)

**Comment by stsp** [comment]
Yes, try using the repo directly,
branch "devel". At the end of configure
process you'll be presented with
the list of possible plugins. See if
X and sdl are there.

Image is mounted the same way
as the directory, no difference at all.

Yes, they build a recent sources,
but that doesn't mean they build
all the plugins.

**Comment by AlbertHamik** [comment]
I'll admit I'm not compiling things manually that often but when I download the dosemu2-devel git to a directory, I can't use ./configure and when reading into it, I read to try autoconf or perhaps autoreconf but it would spit out errors along the lines of macros being obsolete. I would then try out ./configure again only for it to quickly stop with this error: 

`./configure: line 5907: syntax error near unexpected token `SYSCONFDIR,'
./configure: line 5907: `AC_DEFINE_DIR(SYSCONFDIR, sysconfdir,  System config dir )'
`

**Comment by stsp** [comment]
autogen.sh

**Comment by AlbertHamik** [comment]
Okay so it compiled but it didn't ask me about options and the version I successfully compiled won't do anything with X still.

**Comment by AlbertHamik** [comment]
I did a new configure to show what it had given me: https://pastebin.com/crpAQqH1

**Comment by stsp** [comment]
Yes, that was a bug in configure.

**Comment by AlbertHamik** [comment]
I did compile the new thing but it was still having weird random issues and even when I supplied whatever it wanted with regards to X or whatever, it wasn't giving me the ability to open DOSEMU in X11 mode still.

**Comment by stsp** [comment]
Do you have `libplugin_X.so` built?
It is what gets loaded on `-X` so
make sure it is built and ldd shows
no errors on it.

**Comment by AlbertHamik** [comment]
I checked my system and I'm not detecting a `libplugin_X.so`, no. Is it supposed to get compiled with the DOSEMU2 source?

**Comment by stsp** [comment]
Of course, as well as all other
`libplugin_*.so` plugins.

**Comment by AlbertHamik** [comment]
I looked inside my boot log, and I think this is in all of them:
`ERROR: /usr/local/lib/dosemu/libplugin_X.so: cannot open shared object file: No such file or directory`

**Comment by stsp** [comment]
You could as well find that on a
terminal where you start dosemu.

**Comment by AlbertHamik** [comment]
So why is it not compiling in then?

**Comment by stsp** [comment]
See configure output.

**Comment by AlbertHamik** [comment]
This is what autogen.sh and ./configure do, respectively: https://pastebin.com/17JvUfby

**Comment by stsp** [comment]
Warnings should now be fixed, thanks.

**Comment by AlbertHamik** [comment]
autogen is fine now yeh, but this has not solved my problem with trying to compile after running configure. I have here the outputs from using the suggested default configure script and then using make: https://pastebin.com/WvuLSWkg
(I edit out paths but this is accurate to what I see happening)

**Comment by stsp** [comment]
Have you never used configure before?
Its there to check dependencies, and
report if some are missing.
And it does.
There was a bug that allowed to compile
anyway, even with configure error, but it
was fixed.

**Comment by AlbertHamik** [comment]
I mean I've always just relied on instructions on steps to take with compiling stuff that has the make setup with a configure and whatnot. I've never messed with an autogen before until trying to compile DOSEMU2. If you're saying a bug was allowing for the program to compile anyways with missing configure options then what am I supposed to have now for DOSEMU2 to compile? Is it trying to tell me dependencies I need?

**Comment by andrewbird** [comment]
> Is it trying to tell me dependencies I need?

Exactly, configure reports that FDPP is not available and I believe this is fatal for compilation. Essentially, check the output of ./configure for error lines and install what it complains is missing. Only then move on to make.

**Comment by stsp** [comment]
Andrew, why tests are failing again? :)

**Comment by andrewbird** [comment]
Not really sure, there seems to be some apt repository weirdness, but only on Travis. I'll attempt a retry to see if it's fixed itself.

**Comment by andrewbird** [comment]
Nope, same problem. Not sure if there's anything we can fix.
~~~
The following packages have unmet dependencies:
 clang : Depends: clang-10 (>= 10~) but it is not going to be installed
 gcc-multilib : Depends: gcc-9-multilib (>= 9.3.0-3~) but it is not going to be installed
 valgrind : Depends: libc6-dbg but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

The command "./ci_prereq.sh" failed and exited with 100 during .
~~~

**Comment by AlbertHamik** [comment]
Stupid question, but is fdpp going to act as a replacement for the default DOS platform that DOSEMU2 loads up normally? I've been working with a MS-DOS 6.22 image myself as I want to avoid any compatibility issues with the game I've been playing, for which DOSEMU2 has been an absolute lifesaver in getting that to work.

**Comment by AlbertHamik** [comment]
Well anyways I tried compiling both the git and the release source of fdpp and I get this nonsense (edited paths before pasting): https://pastebin.com/3yHCfM8u

**Comment by stsp** [comment]
So you need to install clang++.
Why is this a problem?

**Comment by AlbertHamik** [comment]
Well, okay, I got that now, then I had to get something masm or whatever, and I finally compiled the latest git version of fdpp AND dosemu2... And now it won't start giving me this:

```
ERROR: Neither freecom nor comcom32 installation found.
Use DOSEMU2_EXTRAS_DIR env var to specify location of freedos
or DOSEMU2_COMCOM_DIR env var for alternative location of comcom32
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: hdimage size is not cylinder-aligned (1323 sectors), truncated!
ERROR: BOOT-helper requested, but no systemfile available

```

I did everything you guys said to accomplish this, the recommended configure option apparently enabled all the plugins finally. I don't actually give a crap about FDPP and whatnot, I just wanted to try out X mode to see if the mouse would hook. What in this error message is preventing DOSEMU2 from opening?

**Comment by AlbertHamik** [comment]
I said before, I'm only booting from a MS-DOS 6.22 image right now with KVM settings enabled for a 686 type platform. I don't really need any fancy features, I was simply adding these things hoping it would finally make the X window support happen.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by AlbertHamik** [comment]
Okay, finally I have X mode working... And not only was the mouse not locking still, I also noticed that when I was moving the mouse around and then placed the X mode DOSEMU2 into fullscreen, mouse input was weirdly kinda broken? In a way that was reminiscent though not near as bad as what I experienced when trying to use MSDOS in QEMU. 

Oh right, and sound wasn't working either, at least not for my game using emulated SB16. Not sure how to describe the issue for when I was having it in QEMU, but basically the mouse cursor would have a mind of it's own and keep messing up within the emulated window, causing my FPS-type game to be basically unplayable if any mouse movement happened.

Even though I am currently unable to lock the mouse to a window still, I think even if it did work, X window mode would have major issues with mouse input, at least for my game.

**Comment by stsp** [comment]
> And not only was the mouse not locking still

You need to try changing `$_X_mgrab_key`
setting. SDL plugin disrespects this setting,
which is why you were asked to try X.

> Oh right, and sound wasn't working either,

This is visible even from the errors you showed.
But I won't help you with that.
You have alsa misconfigured in some way.
Please post these errors to alsa mail list,
and maybe they will tell you what you do
wrong.

**Comment by AlbertHamik** [comment]
I did change the X_mgrab_key thing already, and it still won't work. Also, is DOSEMU2 designed to directly load up ALSA, and not pulseaudio? I have sound when running the SDL mode still. I have a hunch the X mode might have issues regardless even if I do solve hooking the mouse as I posited earlier, as even when playing in fullscreen, there seemed to be odd movement issues with the mouse, as if it wasn't aligning properly or something.

**Comment by stsp** [comment]
> I did change the X_mgrab_key thing already, and it still won't work.

On X or on sdl?

> I have sound when running the SDL mode still.

In this case see `man libao.conf` and
create the proper /etc/libao.conf. You
can set it to pulseaudio, so X will get
the sound too.

**Comment by stsp** [comment]
I think all you need is
`default_driver=pulse`
in libao.conf. Although man page
doesn't mention pulse...

**Comment by AlbertHamik** [comment]
> On X or on sdl?

It won't hook for either.

> In this case see `man libao.conf` and
> create the proper /etc/libao.conf. You
> can set it to pulseaudio, so X will get
> the sound too.
>I think all you need is
>default_driver=pulse

That didn't work,  and I did reset in case that needed to be done, too.

**Comment by stsp** [comment]
> It won't hook for either.

I am not asking what will they
hook, I am asking how exactly
you tried it. So for example, you
set `$_X_mgrab_key = "y"` then
run `dosemu -X` and make sure
that X, not sdl plugin started.
Then you press `Ctrl-Alt-y`.
Does something change?
Pay a special attention to the
dosemu2 window title.

> That didn't work

This most likely means your
libao is built w/o pulseaudio
support.
Try `$_sound_driver = "sdl"` then.

**Comment by AlbertHamik** [comment]
I did the change of the bind for mgrab_key and went into dosemu -X and tried, and it wouldn't work. Likewise for SDL mode still but we knew that already. As for the sound driver option, I did that before you told me to and it seemingly made no difference.

**Comment by stsp** [comment]
> and it wouldn't work.

Does window title change?

> I did that before you told me to and it seemingly made no difference,

Should now be fixed.

> X mode also seems to lack aspect ratio correction

In text or gfx mode?
Have you changed $_X_fixed_aspect
and related settings?
Or what do you mean by
"correction"?

**Comment by AlbertHamik** [comment]
> Does window title change?

No it doesn't. I noticed there's an option to manually change the window title and I tested that and there's really no change between X and SDL mode even with a custom title, it's simply the custom title I gave and nothing extra.

> Should now be fixed.

I will compile that and report on if it fixes that for X mode.

> In text or gfx mode?
> Have you changed $_X_fixed_aspect
> and related settings?
> Or what do you mean by
> "correction"?

Having a 4:3 aspect ratio that isn't stretched out to my display. The moment I enter fullscreen X mode gets screwed up. SDL mode displays a seemingly accurate aspect ratio in fullscreen, but not X mode. I tried messing with all the options and X mode just ignores them when I put things in full screen.

**Comment by AlbertHamik** [comment]
And to reiterate, I fear there's some input issue with X mode with the mouse but I can't fully confirm on that without getting mouse hooking to work first.

**Comment by AlbertHamik** [comment]
Well good news, your fix for audio in X mode worked.

**Comment by stsp** [comment]
Yes, fixed aspect is not maintained
under X/fullscreen. But X here is just
to test the grab. not to use it.

Does `Ctrl-Alt-k` work in either X or
sdl mode?

**Comment by AlbertHamik** [comment]
Oh, wow, yeh it works in SDL mode capturing both mouse and keyboard (which if I was ever planning to use an external utility for a timer to capture in OBS, will that hooked keyboard be unable to interact with any universal binds I have set for another application?). In X mode however, it only captures the keyboard.

**Comment by AlbertHamik** [comment]
So I guess the issue has sorta been solved. Though it seems like the ability to bind for mouse hook only is broken?

**Comment by stsp** [comment]
I think Ctrl-Alt-Home is occupied
by your WM, and `$_X_mgrab_key`
is disregarded by SDL plugin, making
that kinda broken for you.
But why  `$_X_mgrab_key` doesn't
work for you also under X, is what
I don't know. It works for me.

**Comment by AlbertHamik** [comment]
mmmh, I want to admit there was user error on my part. I accidentally capitalized whatever letter I tried binding mouse bind to. Now it works in X mode. Still not SDL mode though.

**Comment by AlbertHamik** [comment]
And now that I figured out doing mouse bind for X, I realized to test the game again in windowed X mode, and yeah mouse sensitivity is messed up, though I think it's merely just insanely sensitive rather than broken.

**Comment by stsp** [comment]
I added the support for $_X_mgrab_key.
Please open another ticket for
the mouse problems, properly
filling it according to the reporting
template.

**Comment by AlbertHamik** [comment]
Anyways I think this issue is technically solved for me but SDL mouse hook alone is still broken. I am hoping that can be solved as I think it could be a problem if I have both mouse AND keyboard hooked by DOSEMU2 in what is currently the best option, SDL.

**Comment by AlbertHamik** [comment]
> I added the support for $_X_mgrab_key.
> Please open another ticket for
> the mouse problems, properly
> filling it according to the reporting
> template.

Hope I did that correctly. This might be my first time opening a bug ticket on github.
