### ISSUE TITLE
dosemu2 error after idle more than 5 mnutes

### ISSUE THREAD

**Issue by bpranoto** [dosemu2/dosemu2#1618]
**Describe the bug**
dosemu2 error after idle more than 5 mnutes

**Dosemu version**
```
akunting@akunting:~/master/dosemu2$ dosemu --version
dosemu2-2.0pre9-dev-20220316-85-g76a4e27a4
Revision: 7162

```

**To Reproduce**
Run dosemu, let it is idle for more than 5 minutes
After some time it will be crash

```
akunting@akunting:~/master/dosemu2$ dosemu -D9
ERROR: Coopth: coopth_sched: not in thread!
dosemu.bin: coopth.c:1113: coopth_sched: Assertion `_coopth_is_in_thread()' failed.
removing stale files:
/home/akunting/.dosemu/run/dosemu.dbgin.19705
/home/akunting/.dosemu/run/dosemu.dbgout.19705

```

**Attach program/game binaries or provide an URL**
If the problem needs specific DOS files to reproduce, please attach
or provide the download URL.

**Attach the log**
Attached

**A regression?**
Most likely

[boot.log](https://github.com/dosemu2/dosemu2/files/8510904/boot.log)

**Comment by stsp** [comment]
Should now be fixed, please check.

**Comment by bpranoto** [comment]
I have git pulled and rebuilt the .deb file, unfortunately it still crashes.
[boot.log](https://github.com/dosemu2/dosemu2/files/8517812/boot.log)

**Comment by bpranoto** [comment]
My bad.  It is indeed fixed..

**Comment by stsp** [comment]
Thanks for testing.
