### ISSUE TITLE
TAP issues

### ISSUE THREAD

**Issue by NuSkooler** [dosemu2/dosemu2#1784]
I'm attempting to use dosemu2 over the older dosemu and am running into issues related to TAP. Namely, tap0.

First attempts running dosemu2 with the same configuration I use with dosemu results in:
```
ERROR: PKT: Cannot open tap0: Operation not permitted
ERROR: PKT: Cannot open tap0: Operation not permitted
```

...so I guess it's now up to the user of dosemu to set this up? So I followed this guide:
https://ahelpme.com/linux/centos-8/create-bridge-and-add-tun-tap-device-using-networkmanager-nmcli-under-centos-8/

Now I get the following:
```
ERROR: PKT: Cannot open tap0: Device or resource busy
```

I'm running as such:
```
dosemu -f dosemu.conf -E x:\\qbasic.exe
```

Where my config looks like:
```
$_cpu = "80486"
$_cpu_emu = "vm86"
$_external_char_set = "utf8"
$_internal_char_set = "cp437"
$_term_updfreq = (8)
$_layout = "us"
$_rawkeyboard = (0)
$_com1 = "virtual"
$_sound = (0)
$_speaker = "off"
$_com2 = ""
$_mouse_dev = "com2"
#$_dpmi = (4096)
```

Any help appreciated?

```
dosemu --version
dosemu2-2.0pre9-dev-20220910-400-g637186d43
Revision: 7477
```

AlmaLinux 8,

**Comment by andrewbird** [comment]
It seems you have a permissions problem. In the guide when making the tap device, did you replace owner uid 0 with your own uid that you run Dosemu with?
> nmcli connection add type tun ifname tap0 con-name tap0 mode tap owner 0 ip4 0.0.0.0/24

**Comment by NuSkooler** [comment]
@andrewbird Yep, from my `history`:
```
history | grep 1001
sudo nmcli connection add type tun ifname tap0 con-name tap0 mode tap owner 1001 ip4 0.0.0.0/24
```

Where 1001 is the user ID attempting to execute:
```
id
uid=1001(enigma) groups=1001(enigma) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c102
```

I ran with `strace`. The only reference to `tap0` is the two Permission Denied messages. Nothing from strace itself.

**Comment by andrewbird** [comment]
Did you check syslog, maybe you have appamor or selinux violation?

**Comment by NuSkooler** [comment]
@andrewbird Yep, nothing interesting from `journalctl` or `/var/log/messages`, etc.

**Comment by stsp** [comment]
For dosemu to create new tap device
you need root, so `dosemu -s`.
If you set up tap before starting dosemu,
then you need to specify that device in
dosemu config.

If you dont want to mess with tap devices,
you may find that dosemu2 supports
tcp/ip without tap devices.

HTH.

**Comment by andrewbird** [comment]
I'm sure you are correct, but reading dosemu.conf comments suggest that tap0 should be the default, perhaps they are outdated?

~~~
# Network device for packet driver in "tap" mode.                               
# "" (empty string) means dynamic TAP allocation, which usually requires        
# root privs. The automatically created devices will have the names             
# dosemu_tapN where N is a number.                                              
# Default: "tap0"                                                               
                                                                                
# $_tapdev = "tap0"                                                             
~~~

**Comment by stsp** [comment]
My memory is outdated. :)
Sorry for premature judgement.

**Comment by stsp** [comment]
Should now be fixed.
Looks like a big-deal regression.
Andrew, can you actually check that
ne2k works as expected? Otherwise
I feel like we have an untested code.

**Comment by NuSkooler** [comment]
Just to clarify, I don't *want* to use a TAP device necessarily, but running with the conf I posted, it looks like dosemu2 want it no matter what. In this case, now I *do* have a tap0 which dosemu2 is attempting to access, but still not working, either.

Edit: I'll pull down the latest, compile & test and report back!

**Comment by NuSkooler** [comment]
OK so I pulled down the latest, make && make install. I'm still getting a single
```
ERROR: PKT: Cannot open tap0: Operation not permitted
```

I also see
```
ERROR: term: stderr still on tty, closing
```

Not sure what that one is about, either.

**Comment by andrewbird** [comment]
> Andrew, can you actually check that
ne2k works as expected? Otherwise
I feel like we have an untested code.

I'll see if I can add a couple of tests to the suite using mTCP's htget for both built=in packet driver and http://crynwr.com packet driver over ne2000 in the next few days.

**Comment by stsp** [comment]
> Just to clarify, I don't want to use a TAP device necessarily, but running with the conf I posted,
> it looks like dosemu2 want it no matter what.

This may mean slirp wasn't built.
You might be missing compile-time deps.
This is why we provide pre-built packages,
building from sources may cause troubles.

> OK so I pulled down the latest, make && make install. I'm still getting a single

Is this when you pre-configured
tap0 with the proper UID before
starting dosemu?

> ERROR: term: stderr still on tty, closing

This likely means that even the GUI
back-ends were not built.
Unless you want to use dosemu in
text mode only, you need to satisfy
more compile-time deps.

**Comment by stsp** [comment]
> I'll see if I can add a couple of tests to the suite using mTCP's htget

I think you had some samba troubles,
would be good to check also these.

**Comment by andrewbird** [comment]
I started to write a test for ne2000 / built-in packet driver using mTCP. What's your usual tap configuration as I'm having a little trouble setting it up? I find that I can send packets out (if I use static IP), but the return packets never come because arp cannot be resolved.
I'm hoping to have this test work at Github actions, but I can't start fiddling with the public network. In an ideal world I'd attach my tap interface to the bridge that libvirt already configured (virtbr0).

**Comment by stsp** [comment]
Should now be fixed.
What a junk...

**Comment by andrewbird** [comment]
Thanks that fixed it for the builtin packet driver (although I still get the unanswered arp requests but they don't seem to harm anything). I still have a problem with ne2000 . As you can see from the tshark trace the dhcp offer goes out over the bridge interface, but is never processed by the dhcp program.

#### built-in
~~~
$_pktdriver = (on)                                                              
$_vnet = "tap"                                                                  
$_tapdev = "tap0"                                                               
~~~
~~~
rem c:\ne2000 0x60 10 0x300                                                     
set MTCPCFG=c:\mtcp.cfg
dhcp                                                         
~~~
~~~
Settings written to 'c:\mtcp.cfg'
 
C:\>ping 8.8.8.8
 
mTCP Ping by M Brutman (mbbrutman@gmail.com) (C)opyright 2009-2022
Version: Jul  1 2022
 
Sending ICMP packets to 8.8.8.8
ICMP Packet payload is 32 bytes.
 
Packet sequence number 0 received from 8.8.8.8 in 13.60 ms, ttl=115
Packet sequence number 1 received from 8.8.8.8 in 13.60 ms, ttl=115
Packet sequence number 2 received from 8.8.8.8 in 12.75 ms, ttl=115
Packet sequence number 3 received from 8.8.8.8 in 13.60 ms, ttl=115
 
Packets sent: 4, Replies received: 4, Replies lost: 0
Average time for a reply: 13.38 ms (not counting lost packets)
~~~
~~~
33 313.938854817 192.168.122.204 → 8.8.8.8      ICMP 74 Echo (ping) request  id=0x4860, seq=0/0, ttl=255
34 313.952145858      8.8.8.8 → 192.168.122.204 ICMP 74 Echo (ping) reply    id=0x4860, seq=0/0, ttl=115 (request in 33)
35 314.963404489 192.168.122.204 → 8.8.8.8      ICMP 74 Echo (ping) request  id=0x4860, seq=1/256, ttl=255
36 314.976615042      8.8.8.8 → 192.168.122.204 ICMP 74 Echo (ping) reply    id=0x4860, seq=1/256, ttl=115 (request in 35)
37 315.990711446 192.168.122.204 → 8.8.8.8      ICMP 74 Echo (ping) request  id=0x4860, seq=2/512, ttl=255
38 316.003888275      8.8.8.8 → 192.168.122.204 ICMP 74 Echo (ping) reply    id=0x4860, seq=2/512, ttl=115 (request in 37)
39 317.018803599 192.168.122.204 → 8.8.8.8      ICMP 74 Echo (ping) request  id=0x4860, seq=3/768, ttl=255
40 317.032072058      8.8.8.8 → 192.168.122.204 ICMP 74 Echo (ping) reply    id=0x4860, seq=3/768, ttl=115 (request in 39)
~~~

#### ne2000
~~~
$_pktdriver = (off)                                                             
$_vnet = "tap"                                                                  
$_tapdev = "tap0"                                                               
~~~
~~~
c:\ne2000 0x60 10 0x300                                                         
set MTCPCFG=c:\mtcp.cfg                                                         
dhcp                                                                            
rem end                                                                         
~~~
~~~
System: [345]86 processor, ISA bus, Two 8259s
Packet driver software interrupt is 0x60 (96)
Interrupt number 0xA (10)
I/O port 0x300 (768)
My Ethernet address is 66:62:78:3C:50:BD

C:\>dhcp
mTCP DHCP Client by M Brutman (mbbrutman@gmail.com) (C)opyright 2008-2022
Version: Jul  1 2022
 
Timeout per request: 10 seconds, Retry attempts: 3
Requesting a 3600 second lease
Sending DHCP requests, Press [ESC] to abort.
 
DHCP request sent, attempt 1: Timeout
DHCP request sent, attempt 2: Timeout
DHCP request sent, attempt 3: Timeout
 
Error: Your DHCP server never responded and no packets were seen on the wire.
Check your cabling and packet driver settings, including the hardware IRQ.
~~~

~~~
62 878.755687057      0.0.0.0 → 255.255.255.255 DHCP 302 DHCP Discover - Transaction ID 0xed610000
63 878.755935179 RealtekU_b9:53:ef → Broadcast    ARP 42 Who has 192.168.122.242? Tell 192.168.122.1
64 879.772399272 RealtekU_b9:53:ef → Broadcast    ARP 42 Who has 192.168.122.242? Tell 192.168.122.1
65 880.792402717 RealtekU_b9:53:ef → Broadcast    ARP 42 Who has 192.168.122.242? Tell 192.168.122.1
66 881.759242252 192.168.122.1 → 192.168.122.242 ICMP 62 Echo (ping) request  id=0x3133, seq=0/0, ttl=64
67 881.759329674 192.168.122.1 → 192.168.122.242 DHCP 342 DHCP Offer    - Transaction ID 0xed610000
68 886.904400102 RealtekU_b9:53:ef → 66:62:78:3c:50:bd ARP 42 Who has 192.168.122.242? Tell 192.168.122.1
69 887.932397779 RealtekU_b9:53:ef → 66:62:78:3c:50:bd ARP 42 Who has 192.168.122.242? Tell 192.168.122.1
70 888.760896468      0.0.0.0 → 255.255.255.255 DHCP 302 DHCP Discover - Transaction ID 0xb6e0000
71 888.761204074 192.168.122.1 → 192.168.122.242 DHCP 342 DHCP Offer    - Transaction ID 0xb6e0000
72 893.816397395 RealtekU_b9:53:ef → 66:62:78:3c:50:bd ARP 42 Who has 192.168.122.242? Tell 192.168.122.1
73 894.840400375 RealtekU_b9:53:ef → 66:62:78:3c:50:bd ARP 42 Who has 192.168.122.242? Tell 192.168.122.1
74 895.864405408 RealtekU_b9:53:ef → 66:62:78:3c:50:bd ARP 42 Who has 192.168.122.242? Tell 192.168.122.1
75 898.756991008      0.0.0.0 → 255.255.255.255 DHCP 302 DHCP Discover - Transaction ID 0x9080000
76 898.757286531 192.168.122.1 → 192.168.122.242 DHCP 342 DHCP Offer    - Transaction ID 0x9080000
77 903.800398701 RealtekU_b9:53:ef → 66:62:78:3c:50:bd ARP 42 Who has 192.168.122.242? Tell 192.168.122.1
78 904.824400426 RealtekU_b9:53:ef → 66:62:78:3c:50:bd ARP 42 Who has 192.168.122.242? Tell 192.168.122.1
79 905.848399822 RealtekU_b9:53:ef → 66:62:78:3c:50:bd ARP 42 Who has 192.168.122.242? Tell 192.168.122.1
~~~
log is here 
[ne2000.zip](https://github.com/dosemu2/dosemu2/files/9632251/ne2000.zip)

**Comment by NuSkooler** [comment]
> This may mean slirp wasn't built. You might be missing compile-time deps. This is why we provide pre-built packages, building from sources may cause troubles.

I will double check this. Building from source is not new to me in any way. It's something we should be able to do.

> This likely means that even the GUI back-ends were not built. Unless you want to use dosemu in text mode only, you need to satisfy more compile-time deps.

I don't want a GUI backend. I run the 'legacy' dosemu headless in order to fire up and emulate COMx via stdin/out allowing old DOS game/app/doors to run under my BBS. 

I don't need or want network support for this, but thus far it seems to enforce it. 

I'm really just wanting to replace the legacy dosemu with this new version as it's actively developed and thus I imagine many games that dosemu struggles with should work.

**Comment by stsp** [comment]
> I don't want a GUI backend.

Ah then I guess I know why you
got an error you mentioned.
Normally in text mode you should
start as `dosemu -t`. But in your
case it falls back to text mode by
the lack of other modes, not by
the -t switch.
You can safely ignore that error
then, or use `dosemu -t`.

> I don't need or want network support for this, but thus far it seems to enforce it.

It doesn't enforce, i.e. you can
ignore also that error, or compile
in the slirp support so the error
will disappear, or disable network
in a config.
So its not really enforced. Its just
that we had no automatic tests
for networking, and things got
badly broken in that area. :(

**Comment by stsp** [comment]
Should now be fixed.

**Comment by stsp** [comment]
> $_pktdriver = (off)  

Note that you don't need to do that.
It is supposed to work together with
pkt, so please test also that scenario.

**Comment by andrewbird** [comment]
I got whinges about the interrupt 0x60 being in use when I wanted to load the crynwr packet driver.

**Comment by stsp** [comment]
Sure thing, specify 0x61 then.

**Comment by andrewbird** [comment]
Cool, thanks that fixes it for ne2000 too!

**Comment by stuaxo** [comment]
^ Might be worth adding a note to the dos about using 0x61 for ne2000 + crynwr  ?

**Comment by andrewbird** [comment]
I modified the test to have both packet drivers loaded
~~~
C:\>pkttool scan
 
mTCP pkttool by M Brutman (mbbrutman@gmail.com) (C)opyright 2012-2022
Version: Jul  1 2022
 
Scanning:
 
Details for driver at software interrupt: 0x60
  Name: Linux$
  Entry point: F000:F57A
  Version: 1   Class: 1   Type: 12  Interface Number: 1
  Function flag: 2  (basic and extended functions)
  Current receive mode: all packets (promiscuous mode)
  MAC address: 66:62:78:DC:18:56
 
Details for driver at software interrupt: 0x61
  Name: NE2000
  Entry point: 00B3:03CE
  Version: 11   Class: 1   Type: 54  Interface Number: 0
  Function flag: 2  (basic and extended functions)
  Current receive mode: packets for this MAC and broadcast packets
  MAC address: 66:62:78:DC:18:56
~~~

So should the MAC addresses be the same? Will it hurt, it seems to work okay, but do both built-in and ne2000 receive an incoming packet?

**Comment by andrewbird** [comment]
Actually, to answer my own question, I realised I was only testing ne2000 with the crynwr ne2000 driver loaded. If I load ne2000.com at address 0x61, then test builtin packet driver it can't get an address.

**Comment by stsp** [comment]
Yes, indeed, I haven't implemented
any separation. ne2k just overtakes
all traffic.
I don't think there going to be a use-case
for multiple network interfaces at once.
It may be rather simple to implement
though: you just need a separate MAC
address for each, and you need to
deliver packets to both subsystems,
rather than to just one, as I did now.
And both of those look trivial.
So would you like to do that for the
sake of a testing? :)

**Comment by stsp** [comment]
> ^ Might be worth adding a note to the dos about using 0x61 for ne2000 + crynwr ?

Not unless you are going to
transfer the networking doc
to wiki and add an info about
ne2k itself first.
So maybe you do? :)

**Comment by andrewbird** [comment]
> So would you like to do that for the
sake of a testing? :)

No point in implementing stuff just to please the tests, I'll switch the test back to just load/enable the relevant packet driver.

**Comment by stsp** [comment]
No, its dynamic!
You don't need to disable anything.
Before you load ne2k driver,
packet driver works fine.

**Comment by andrewbird** [comment]
Okay, that's fine too. Actually that's how it was working for me an hour ago.

BTW I think there was a packet based utility that used UDP to communicate between its linux server component and a dos redirector. I can't remember what it was called, I'm pretty sure it had 'eth' in the name, but searching on the Internet for that gives too many results. Does anyone remember what what it's called?

**Comment by stsp** [comment]
And what it did?
Host fs access?
Try msclient+samba - same
thing, and you already said
there were some problems
to test for.

**Comment by andrewbird** [comment]
> Host fs access?

Yes

> Try msclient+samba - same
thing, and you already said
there were some problems
to test for.

I think that's a dead duck. The current Samba has intentionally dropped support for the old protocols and encryption that msclient uses. At the time I tested it here, my Samba was old enough to support it, but that's no longer the case. I suppose running an older distro in a VM is possible, but it's not something that I think we'd want to pull a 500MB image down for each test run.

**Comment by andrewbird** [comment]
I found it http://etherdfs.sourceforge.net/

**Comment by stsp** [comment]
Cool although NFS also seems
to be possible:
https://freedos.sourceforge.net/wiki/index.php/NFS_on_DOS

**Comment by andrewbird** [comment]
I'm going to pause on adding any more network tests for now, as I need to get back to the disk/partition/label stuff before I totally forget what I'm doing there.
Thanks.
