### ISSUE TITLE
Certain programs (BBS door games) run very slowly (which did not happen with dosemu 1.4)

### ISSUE THREAD

**Issue by EricOulashin** [dosemu2/dosemu2#1908]
**Describe the bug**
I'm currently using dosemu2 2.0~pre9-7909-cd0af3bee+202302162016~ubuntu22.04.1_amd64

I run an old-style BBS (bulletin board system) with some online games, and with dosemu2, I've noticed some of the 16-bit DOS online door games run very slowly with very high CPU usage in dosemu2 (this did not happen with dosemu 1.4).

After running the DOS programs, if you run top, you can see high CPU usage from dosemu.

**To Reproduce**
Download [this zip file](http://www.digitaldistortionbbs.com:81/bbsStuff/dosemu2Stuff/doors.zip).
Make a directory and configure it as the D drive for dosemu.  Copy DOOR.SYS to that directory.
Run dosemu configured with a D drive.

Command lines for the included programs:

TRIVIA_S:
TRIVIA.EXE TRIVIA.CFG

FACTS:
FACTS.EXE FACTS1.CFG

STREKTRV:
TRKTRV.EXE TREKTRV1.CFG

**Attach program/game binaries or provide an URL**
Download [this zip file](http://www.digitaldistortionbbs.com:81/bbsStuff/dosemu2Stuff/doors.zip)

**Attach the log**
Log and dosemu.conf is available in a zip file [here](http://www.digitaldistortionbbs.com:81/bbsStuff/dosemu2Stuff/dosemu2.zip).

**Comment by stsp** [comment]
Wow, star trek?
Lets see how does it compare to my sst2k :)
https://github.com/stsp/sst2k

**Comment by stsp** [comment]
These games cannot detect ansi for me.
How do you get around that problem?
Please provide the ansi.sys that you use.

**Comment by EricOulashin** [comment]
I don't use an ansi.sys. I normally play these remotely and the BBS
terminal I use supports ANSI

**Comment by stsp** [comment]
Should now be fixed then.

**Comment by EricOulashin** [comment]
I installed 2.0_pre9-7919-fa6246ca5+202302182016_ubuntu22.04.1_amd64 just
now, and I'm still seeing the same slowness and high CPU usage.
[image: image.png]

**Comment by EricOulashin** [comment]
> Should now be fixed then.

I installed 2.0_pre9-7919-fa6246ca5+202302182016_ubuntu22.04.1_amd64 just now, and I'm still seeing the same slowness and high CPU usage.   I ran TRIVIA.EXE under TRIVIA_S and top shows 100% CPU usage for dosemu.bin

**Comment by stsp** [comment]
In this case the first step is to remove
the full crap from your config.
For trivia.exe I only have 1 line in
.dosemurc:
`$_hdimage = "+0 -1 +1"`
It is needed to vacate drive D.
I also have 1 line in userhook.sys:
`devicehigh=c:\bin\nansi.sys`

Then I go to the directory where
I unpacked your archives (which
will be drive D) and type this:
`dosemu -K ./:TRIVIA_S -E "trivia.exe trivia.cfg"`

Please do exactly the same and
let me know the results.

**Comment by EricOulashin** [comment]
What ANSI.SYS are you using?  When I add devicehigh=c:\bin\ansi.sys, then
dosemu2 immediately exits when I try to run it.

**Comment by stsp** [comment]
I am using nansi.sys from freedos.
If it exits with the options I posted above,
then add -T1 to them to avoid exiting.

**Comment by stsp** [comment]
In 9db46279a2 I applied a different
fix. Please see again.

**Comment by EricOulashin** [comment]
I've installed dosemu2 2.0-pre9-7929 202302202016 and still see the high
CPU usage/slowness.
