### ISSUE TITLE
FreeCOM in -dumb -td -kt mode: Entering the first effective backspace outputs many blank lines

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#1921]
**Describe the bug**
When running a recent (today's) revision of dosemu2, using fairly recent FreeDOS kernel and FreeCOM, in `-dumb -td -kt` mode, then the first backspace pressed at the FreeCOM prompt that actually is meant to delete a character, will not delete the character and instead output enough blank lines to completely fill the current terminal's screen space.

(The original `C:\>` prompt is still visible in the very first line of the terminal. If the character entered before the backspace keypress is printable, it is also still shown in that first line, not overwritten with a blank. The last line will contain one blank and after that the blinking cursor.)

This problem does not affect my debugger, which uses either interrupt 21h service 0Ah or its own line editor which reads byte-wise using service 08h.

This problem does not occur with either `dosemu -t` or `dosemu -dumb` without the other switches.

I guess this may be a FreeCOM bug. I'll have to look more into it.

**To Reproduce**
1. Run `dosemu -dumb -td -kt`
2. Enter a key like "X"
3. Enter Backspace

**Attach program/game binaries or provide an URL**
https://pushbx.org/ecm/test/20230222/ There's `kernel.sys` and `command.com` that I used in these tests.

**Attach the log**
https://pushbx.org/ecm/test/20230222/1550.log

**A regression?**
Does not happen on old `Build 2.0pre8-20191102-1332-g9cf2b7560`, though this also does not properly erase the first character when pressing "X" then backspace. But no blank lines spam in that case.

**Additional info**
As mentioned using FreeDOS kernel and FreeCOM.

**Screenshots**
Before entering anything:
![Screenshot_20230222-155005](https://user-images.githubusercontent.com/31538682/220728072-54c61924-23d8-4346-ba46-3840dc9665c7.png)

After entering one Space then one time Backspace:

![Screenshot_20230222-155017](https://user-images.githubusercontent.com/31538682/220728153-efa99e7f-52d8-4d32-9036-1ec31f67530e.png)

**Comment by ecm-pushbx** [comment]
The `ver /r` command says:

```
FreeCom version 0.85a - WATCOMC - XMS_Swap [Jul 10 2021 19:28:06]
DOS version 7.10
FreeDOS kernel - GIT (build 2043 OEM:0xfd) [compiled May 22 2022]
```

**Comment by ecm-pushbx** [comment]
Upgraded to `FreeCom version 0.85a - GNUC - XMS_Swap [Nov  7 2022 23:57:11]`, same problem. (This is the `command.com` from today's https://pushbx.org/ecm/download/freecom.zip which will eventually move to https://pushbx.org/ecm/download/old/freecom/20221107.zip if a new build happens.)

**Comment by stsp** [comment]
Interesting behavior.
I think it works fine without `-kt`
because then there is a local
editing, and the command is sent
only after pressing Enter. But in
-kt mode all keys are sent.
With comcom32 backspace does
not produce any effect in -kt mode
(even the desired effect is missing),
so I suppose -kt has backspace
broken.

**Comment by ecm-pushbx** [comment]
Just tested again, the debugger works fine, both with `r DCO or= 800` to use its own line editor and without to use DOS interrupt 21h function 0Ah. The left arrow key does not work with the DOS service but does work with my own line editor.

**Comment by ecm-pushbx** [comment]
keybtest gets 0E08h for a backspace keypress, same in `dosemu -dumb -td -kt` as in `dosemu -t`

**Comment by stsp** [comment]
Right, and I was wrong about comcom32.
There is a desired effect of a backspace,
its just not visible.
In that case the problem is somewhere
in output, not input. As freecom is probably
trying to edit the line by outputting some
control chars, which add extra newlines
in a dumb mode.

**Comment by ecm-pushbx** [comment]
I tried tracing FreeCOM's output, using these commands:

```
ldebug.com c:\command.com
bp new ptr ri21p when ah < d || ah == 40
r dco or= 8
re.append @if (ah == 40 && cx != 0) then d ds:dx l cx
r dco or= 4000
```

Then enter the "KEEP" keyword to serial terminal, put a "G" command, then keep pressing Enter (autorepeat command) to the serial terminal to see the int 21h calls that do character I/O (int 21h services ah < 0Dh or ah == 40h). This is what it shows when the blank lines happened:

![Screenshot_20230223-180949](https://user-images.githubusercontent.com/31538682/220979643-f2f48be2-d572-491c-95bb-faa45c052ffa.png)

I don't know if it does anything to int 10h, I'll try figuring that out next.

**Comment by stsp** [comment]
Yes, the problem seems with freecom.
In non-dumb mode it handles backspace
this way:
- does direct crtc write to reposition cursor
- writes the space to overwrite char

But in dumb mode it uses int10 fn 2 to
position cursor, and the values are very
wrong. I think it has some untested
fall-back for a dumb mode. But I wonder
how does it even detect the dumb mode?

**Comment by ecm-pushbx** [comment]
Yep, got the same results, I did the following to test:

```
ldebug.com c:\command.com
r dco or= 4008
```

On the serial terminal:

```
keep
bp new ptr ri10p
install timer
bd all
g
(Double Control-C)
be all
g
```

Then enter "x" then Backspace to the FreeCOM terminal, while submitting empty (autorepeat) commands to the serial terminal. Result:

![Screenshot_20230223-182338](https://user-images.githubusercontent.com/31538682/220983774-dcde1210-44ae-4d95-b6fe-57376c13c74a.png)

**Comment by ecm-pushbx** [comment]
https://github.com/FDOS/freecom/blob/b6d58cfa44093680c69bb9d2fdb28a574413f343/lib/cmdinput.c#L20

**Comment by ecm-pushbx** [comment]
https://github.com/FDOS/freecom/blob/b6d58cfa44093680c69bb9d2fdb28a574413f343/lib/cmdinput.c#L158

**Comment by stsp** [comment]
So it detects the dumb mode very
easily: by doing get video mode.
If mode is 0 then dumb, if mode is
3 then OK. Lets cheat it a bit then...

**Comment by ecm-pushbx** [comment]
Where do you see that in the sources? I only see its use of `wherex` and `wherey`, which will not work correctly in `-dumb` mode.

**Comment by stsp** [comment]
Not in sources, I've found that by
trial and error. If it got mode 3 then
it doesn't do gotoxy(), in mode 0 it
does. But I've found a simpler fix
after all. :)

**Comment by ecm-pushbx** [comment]
Your change does fix that bug but it introduces blank lines in a different way:

![Screenshot_20230223-194059](https://user-images.githubusercontent.com/31538682/221000715-ca9c70d0-d7a0-49cb-864d-8ea836384748.png)

**Comment by ecm-pushbx** [comment]
Not sure about reproducibility, the problem just went away in the middle of a session: 
![Screenshot_20230223-194426](https://user-images.githubusercontent.com/31538682/221001380-6e12f15e-e06a-4034-a601-89b26cbd1ea7.png)

**Comment by ecm-pushbx** [comment]
Seems like it's "fixed" after some amount of output.

**Comment by ecm-pushbx** [comment]
lDebug's register change highlighting to int 10h terminal is broken with this change too:

![Screenshot_20230223-200922](https://user-images.githubusercontent.com/31538682/221006561-1784fd78-b8ce-44b6-bbde-f45e06ccda6f.png)

At a glance probably the detection thinks the `-dumb -td -kt` terminal is functional for video attributes where it isn't. That code is around https://hg.pushbx.org/ecm/ldebug/file/628d08c5afee/source/lineio.asm#l831

**Comment by ecm-pushbx** [comment]
Traced it, that's exactly what happens. When highlighting the first register (after text `AX=`), `dl` becomes nonzero from the 10.03 call:

```
AX=0E1B BX=0007 CX=004C DX=E972 SP=F096 BP=F066 SI=E976 DI=E9C1
DS=2ACB ES=2ACB SS=2ACB CS=39D6 IP=E2F9 NV UP EI PL ZR NA PE NC
39D6:E2F9 B403              mov     ah, 03
-t
AX=031B BX=0007 CX=004C DX=E972 SP=F096 BP=F066 SI=E976 DI=E9C1
DS=2ACB ES=2ACB SS=2ACB CS=39D6 IP=E2FB NV UP EI PL ZR NA PE NC
39D6:E2FB 8A3E610C          mov     bh, [0C61]                       DS:0C61=00
-
AX=031B BX=0007 CX=004C DX=E972 SP=F096 BP=F066 SI=E976 DI=E9C1
DS=2ACB ES=2ACB SS=2ACB CS=39D6 IP=E2FF NV UP EI PL ZR NA PE NC
39D6:E2FF 31D2              xor     dx, dx
-
AX=031B BX=0007 CX=004C DX=0000 SP=F096 BP=F066 SI=E976 DI=E9C1
DS=2ACB ES=2ACB SS=2ACB CS=39D6 IP=E301 NV UP EI PL ZR NA PE NC
39D6:E301 CD10              int     10
-
AX=031B BX=0007 CX=0A0B DX=3603 SP=F096 BP=F066 SI=E976 DI=E9C1
DS=2ACB ES=2ACB SS=2ACB CS=39D6 IP=E303 NV UP EI PL ZR NA PE NC
39D6:E303 84D2              test    dl, dl
-
```

**Comment by stsp** [comment]
Should now work better.

So if you traced the check, where
is it in the sources?

**Comment by ecm-pushbx** [comment]
I was referring to my debugger's check for whether it can use video attributes, which I linked in the prior comment:

> At a glance probably the detection thinks the `-dumb -td -kt` terminal is functional for video attributes where it isn't. That code is around https://hg.pushbx.org/ecm/ldebug/file/628d08c5afee/source/lineio.asm#l831

This check is supposed to fail in `-dumb` mode so that the debugger will assume a terminal which accepts escape sequences, and send those to int 10h, instead of trying to muck with the video attributes which doesn't work correctly in `-dumb` mode.

**Comment by ecm-pushbx** [comment]
Empty lines gone, FreeCOM fixed, debugger DCO3 flag 40000h + DCO flag 8 still broken.

**Comment by stsp** [comment]
So why non-zero return of a cursor
position is called "still broken"?

**Comment by ecm-pushbx** [comment]
> So why non-zero return of a cursor position is called "still broken"?

I depend on getting zero (despite having written at least one codepoint to the current line) in order to detect dosemu `-dumb` mode. I want to handle `-dumb` mode differently than modes with actual, working text video buffers/attributes. If you know a better way to detect modes please enlighten me.

**Comment by stsp** [comment]
But even freecom knows: get_mode returns
0 instead of 3. And attempt to set any mode
returns error.

**Comment by ecm-pushbx** [comment]
I can't test by trying to set a mode. Is the "mode 0" return reliable for detecting `-dumb` mode?

**Comment by ecm-pushbx** [comment]
There is no `get_mode` function in FreeCOM. Can you show me where it queries a video mode?

**Comment by stsp** [comment]
Not entirely reliable: maybe you are
indeed working with mode 0?
But you can double-check: get mode
and if it is 0, try to set same mode 0.
Even that should fail.

I don't know where does it do this.
But I clearly see in the log that when
it detects dumb mode (via get video
mode) then it is trying to use int10
for cursor positioning, whereas otherwise
it directly prints a backspace char.
This is a bit weird, it could do the opposite.

**Comment by ecm-pushbx** [comment]
> Not entirely reliable: maybe you are indeed working with mode 0?

Yes, according to the list http://fd.lod.bz/rbil/interrup/video/1000.html#table-00010 mode 0 is a valid text mode.

> But you can double-check: get mode and if it is 0, try to set same mode 0. Even that should fail.

But that will reset the screen contents. You could try setting mode `80h | 0` but according to the list (above link):

> Notes:	IBM standard modes do not clear the screen if the high bit of AL is set (EGA or higher only)

So that also isn't very portable.

Can I get a flag (default off or default on) to retain the 10.03 `dx=0` return?

**Comment by ecm-pushbx** [comment]
Anyway what does "fail" mean? How do you detect that the 10.00 call failed? The list doesn't mention anything.

**Comment by stsp** [comment]
I can set CF for you. :)

**Comment by stsp** [comment]
Possibly on get mode too?
Then no need to re-check.

**Comment by ecm-pushbx** [comment]
That doesn't seem very useful when no CF state is part of the interface usually.

**Comment by stsp** [comment]
Is "cursor pos stuck to 0" a part of
an interface? dosemu detection is
never a part of any bios interface.

**Comment by ecm-pushbx** [comment]
I don't know any false positives or false negatives of that test before your patches today.

**Comment by stsp** [comment]
You asked to fix freecom cursor positioning.
I did.
You are unhappy. :)
Sorry.

**Comment by ecm-pushbx** [comment]
I can just make a TSR that forces the `dx=0` return but ideally it would have a reliable way to detect dosemu in `-dumb` mode.

**Comment by ecm-pushbx** [comment]
The FreeCOM bug can be handled on FreeCOM side as well, checking that the cursor position isn't all zeroes. Except that probably would fail now too.

**Comment by stsp** [comment]
That reliable detect shouldn't break
progs that query cursor position.
I propose you CF: it breaks nothing.

**Comment by ecm-pushbx** [comment]
CF could break with other video BIOSes.

**Comment by stsp** [comment]
In what way?
CF is either clear on success, or at
least preserved (so you may clear it
before call)

**Comment by ecm-pushbx** [comment]
Could be CF is set by another video BIOS, BIOS doesn't always return with `iret`. This is too far from the functionality I actually want to test. Perhaps just add a new service (on a dosemu interrupt like int E6h?) which is backwards-"compatible" by not existing in dosemu before now? I can do the usual dosemu check [like in my quit program](https://hg.pushbx.org/ecm/ldebug/file/628d08c5afee/misc/quit.asm).

**Comment by stsp** [comment]
Helper is already there, `DOS_HELPER_GET_TERM_TYPE`

**Comment by ecm-pushbx** [comment]
> Helper is already there, `DOS_HELPER_GET_TERM_TYPE`

Thanks, I added the detection in https://hg.pushbx.org/ecm/ldebug/rev/148042f226dd

I got the function number from https://github.com/dosemu2/dosemu2/blob/19b1374c5e24584b4735eed08ddb92c61486ef8c/src/include/doshelpers.h#L105 and the flag 100h for `ax` from the implementation in https://github.com/dosemu2/dosemu2/blob/19b1374c5e24584b4735eed08ddb92c61486ef8c/src/base/core/int.c#L670

**Comment by ecm-pushbx** [comment]
Checked in most recent revision in `-dumb -td -kt` and `-t` modes and they both work, former sends escape sequences to terminal while latter changes video attributes instead.

**Comment by stsp** [comment]
Yes, -kt mode is quite weird. I added it
when slang with utf8 support was not yet
in all distros. Maybe it should be removed
because it exposes raw terminal codes
to dos.

**Comment by ecm-pushbx** [comment]
Not sure what codes you mean, but in https://hg.pushbx.org/ecm/ldebug/file/148042f226dd/source/lineio.asm#l2677 I rely on getting special codes for the arrow keys, Home, and End. And ASCII 08h or 7Fh for Backspace. Please don't remove my ability to use those!

**Comment by stsp** [comment]
Unless you make sure your code
works in -t mode, I will remove your
ability to use that. :)

**Comment by ecm-pushbx** [comment]
> Unless you make sure your code works in -t mode, I will remove your ability to use that. :)

I think it does work in `-t` mode, as well as in X window or SDL window. `-dumb -td -kt` is just more convenient for me to use, as I can scroll back the terminal (using `screen`) which doesn't work with `-t`.

**Comment by stsp** [comment]
Good, in this case you should not
get any difference, lets see.
Patch follows soon.

**Comment by stsp** [comment]
Please check, -kt should now work
similar to -t for keyboard.

**Comment by ecm-pushbx** [comment]
Left arrow only sends the `2044 "D"` keypress to keybtest.com instead of the escape sequence.

**Comment by ecm-pushbx** [comment]
This is unlike `-t` where left arrow sends a `4B00` keypress.

**Comment by ecm-pushbx** [comment]
Home and End appear to work as intended, sending `4700` and `4F00` keypress codes.

**Comment by stsp** [comment]
I don't know what you mean.
Escape sequences will not be sent
any more, but I see 4be0 for left arrow,
which is neither 2044 nor 4b00 from
your message.

**Comment by stsp** [comment]
Also I see no difference between `-t`
and `-dumb -kt`, they both now send
4be0.

**Comment by ecm-pushbx** [comment]
Well, that's not what I get (for `-dumb -kt` or `-dumb -td -kt`). I'm using ConnectBot 1.9.6-oss, connecting to OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022, running Screen version 4.08.00 (GNU) 05-Feb-20, and running dosemu in screen.

If I run without screen I get the expected keypress.

**Comment by stsp** [comment]
Then its not a dosemu problem obviously.

**Comment by ecm-pushbx** [comment]
It's a regression though. It used to work, now it doesn't.

**Comment by ecm-pushbx** [comment]
Okay, it works fine if I pass `TERM=xterm` to the dosemu command. Some weird incompatibility of the default (`screen-256color`).

**Comment by stsp** [comment]
To the dosemu command?
But in that case it would only appear under
dos env...

**Comment by ecm-pushbx** [comment]
F11 and F12 don't work with current dosemu in TERM=xterm. They send escape sequences with older dosemu with `TERM=xterm` in `-dumb -td -kt` mode:

```
011B
1A5B "["
0332 "2"
0433 "3"
297E "~"
011B
1A5B "["
0332 "2"
0534 "4"
297E "~"
```

**Comment by ecm-pushbx** [comment]
> To the dosemu command? But in that case it would only appear under dos env...

I pass `TERM=xterm` to bash before the dosemu command, like so:

```
$ TERM=xterm dosemu -dumb -td -kt -K "$PWD" -E keybtest.com
```

**Comment by ecm-pushbx** [comment]
~~F11 and F12 work fine in today's dosemu with `TERM=xterm dosemu -t` as opposed to `TERM=xterm dosemu -dumb -td -kt`~~ No they don't, no response either.

**Comment by stsp** [comment]
The only explanation I can think of, is that
screen-256color throws scan codes instead
of escapes? Because -td did no translation
before, so if that somehow worked, then
screen did?
Anyway. It doesn't work to claim "it works
this and that way, your patch regresses,
dont steal my ability to use something"
and only 10 messages later one finds out
that you throw dosemu on this and that
software that no one else ever used.

**Comment by ecm-pushbx** [comment]
Edited the prior comment, F11 and F12 are broken with `TERM=xterm dosemu -t` too.

**Comment by ecm-pushbx** [comment]
> Anyway. It doesn't work to claim "it works
this and that way, your patch regresses,
dont steal my ability to use something"
and only 10 messages later one finds out
that you throw dosemu on this and that
software that no one else ever used.

Well that doesn't really change that your change breaks my use case.

**Comment by ecm-pushbx** [comment]
With showkey I do get keypresses for F11 and F12.

```
$ TERM=xterm showkey -a

Press any keys - Ctrl-D will terminate this program

^[[23~   27 0033 0x1b
         91 0133 0x5b
         50 0062 0x32
         51 0063 0x33
        126 0176 0x7e
^[[24~   27 0033 0x1b
         91 0133 0x5b
         50 0062 0x32
         52 0064 0x34
        126 0176 0x7e
```

**Comment by ecm-pushbx** [comment]
With `TERM=xterm-color dosemu` F11, F12, and arrow keys work but F1, F2, etc give digit keys.

**Comment by ecm-pushbx** [comment]
I don't understand why (with the default `TERM=screen` or `TERM=screen-256color`) arrow keys don't work in current `dosemu -dumb -td -kt` but do work in `dosemu -t`. How do these differ?

**Comment by ecm-pushbx** [comment]
Okay, I found something else. *Outside* screen my default is `TERM=xterm-256color` and new `dosemu -dumb -td -kt` is as follows:

 * arrow keys work
 * F1 works
 * F11 and F12 give no response

**Comment by stsp** [comment]
So in -t and -kt modes F12 gives me d858.
I can't reproduce any difference.
But of course it is possible that some part
of the screen init in term plugin is needed
for kbd part. This would be difficult to find
out as long as for me there are no differences.

**Comment by ecm-pushbx** [comment]
With `TERM=xterm-256color dosemu -dumb -td -kt` or `TERM=xterm-256color dosemu -t` (today's dosemu, both outside screen) I occasionally get an F11 response if I spam the key for a minute. It looks like this:

```
011B
1A5B "["
0332 "2"
0433 "3"
297E "~"
```

Any idea why dosemu usually doesn't respond to this key?

**Comment by stsp** [comment]
See -D9+k log.

**Comment by stsp** [comment]
Though in my case F11 is hooked by
WM, but f12 works.

**Comment by ecm-pushbx** [comment]
> So in -t and -kt modes F12 gives me d858.

ASCII 58h? That's "X". I don't think F12 should give "X"?

> I can't reproduce any difference. But of course it is possible that some part of the screen init in term plugin is needed for kbd part. This would be difficult to find out as long as for me there are no differences.

Can any log options of dosemu help?

**Comment by stsp** [comment]
> ASCII 58h? That's "X". I don't think F12 should give "X"?

First you read 58 from port 0x60,
then 0xd8.

> Can any log options of dosemu help?

See above msg.

**Comment by ecm-pushbx** [comment]
I created the log from `TERM=xterm-256color dosemu -dumb -td -kt -K "$PWD" -E keybtest -D9+k` outside screen, pressing Left, Down, Right, Up, F1 (and F2 then I think?), then F11 and F12. It's at https://pushbx.org/ecm/test/20230224/1318.log

**Comment by ecm-pushbx** [comment]
> > ASCII 58h? That's "X". I don't think F12 should give "X"?
> 
> First you read 58 from port 0x60, then 0xd8.

I don't know anything about port 60h, I'm referring to keybtest.com outputs (which are `ax` return values from int 16h, ie match what the application will see). Program included in https://pushbx.org/ecm/test/20230224/

> > Can any log options of dosemu help?
> 
> See above msg.

Yes, thanks.

**Comment by stsp** [comment]
With keybtest I get nothing from F12
in all modes, even in SDL. So I don't
think its a regression.

**Comment by ecm-pushbx** [comment]
If someone can help me make sense of this, 

https://pushbx.org/ecm/test/20230224/1342.log is from `TERM=screen-256color dosemu -K "$PWD" -E "keybtest.com" -dumb -td -kt -D9+k` under screen pressing Left Arrow then Enter. This displays keybtest output `2044 "D"`

https://pushbx.org/ecm/test/20230224/1343.log is almost the same but with `-t`, from `TERM=screen-256color dosemu -K "$PWD" -E "keybtest.com" -t -D9+k`  under screen also pressing Left Arrow then Enter. This displays `4B00` as expected.

**Comment by andrewbird** [comment]
Just as an additional datapoint with yesterday's PPA I do get something from F12 with -td, but nothing in -S, -X, or -t

~~~
C:\>keybtest
011B
1A5B "["
0332 "2"
0534 "4"
297E "~"
~~~

**Comment by ecm-pushbx** [comment]
> With keybtest I get nothing from F12 in all modes, even in SDL. So I don't think its a regression.

I can get something from F11 and F12 with 16.10 calls using `TERM=xterm-256color dosemu -K "$PWD" -E "ldebug /c'a 111;mov ah,10;.;g' keybtest.com" -dumb -td -kt -D9+k` in screen. Following output is from pressing Left, Down, Right, Up, F1, F2, F11, F12. Is this intended?

```
Welcome to dosemu2!
    Build 2.0pre9-dev-20230224-923-gd308c1bef
&a 111
2158:0111 mov ah,10
2158:0113 .
&g
4BE0
50E0
4DE0
48E0
3B00
3C00
8500
8600

Program terminated normally (0000)
-q
```

**Comment by ecm-pushbx** [comment]
16.09 isn't supported by dosemu it appears. This is a way to detect 16.10 support. Any idea how else to detect 16.10 support? http://fd.lod.bz/rbil/interrup/bios/1609.html

**Comment by stsp** [comment]
That's the deal, good spot.

**Comment by ecm-pushbx** [comment]
From some versions of `dosemu -t` I got these codes:

```
kbF11		equ	5400h
kbF12		equ	5500h
```

Source: https://hg.pushbx.org/ecm/insight/rev/0e4dc27ddb60

These are differing from the 16.10 returns for these keys. And this was returned by 16.00 as Insight as yet only uses 16.00: https://hg.pushbx.org/ecm/insight/file/0e4dc27ddb60/src/keyboard.inc#l141

According to the interrupt list on int 09h scancodes are a big mess, including the ones for F11 and F12: http://fd.lod.bz/rbil/interrup/hardware/09.html

I don't get how dosemu can return scancode 85h/86h for F11 and F12, usually the high bit set would be a key release event.

**Comment by ecm-pushbx** [comment]
This https://www.stanislavs.org/helppc/scan_codes.html does list 8500h and 8600h. But the arrow keys shouldn't have E0h in the lower byte according to this. Wouldn't be much of a hassle to translate xxE0h to xx00h though, if it is consistent.

**Comment by stsp** [comment]
One step at a time, please.
I added 09.
Does this help?

**Comment by ecm-pushbx** [comment]
Yes, it does, thanks. That will allow changing the applications to use 16.10 instead.

**Comment by stsp** [comment]
> But the arrow keys shouldn't have E0h in the lower byte according to this.

From keybtest I am not getting any
E0 for arrow keys.
Now why keybtest doesn't display the
codes for F12? Because the high bit
is set? Note that on terminal the press
and release events are generated in
a rapid succession, so you'll get both.

**Comment by ecm-pushbx** [comment]
> > But the arrow keys shouldn't have E0h in the lower byte according to this.
> 
> From keybtest I am not getting any E0 for arrow keys. Now why keybtest doesn't display the codes for F12? Because the high bit is set? Note that on terminal the press and release events are generated in a rapid succession, so you'll get both.

No, F12 keypresses are swallowed by 16.00, which keybtest exclusively uses. As I wrote in another message you need to patch keybtest to use 16.10 to see F12. This also seems to change things so dosemu returns xxE0 for eg arrow keys.

Command to run patched keybtest: `-E "ldebug /c'a 111;mov ah,10;.;g' keybtest.com"`

**Comment by stsp** [comment]
Why not to upload the updated binary?

**Comment by ecm-pushbx** [comment]
Added as https://pushbx.org/ecm/test/20230224/ke10test.com

**Comment by stsp** [comment]
Good so I've got 8600 for F12 in
all modes and arrow is also consistent.
Where is the problem?

**Comment by ecm-pushbx** [comment]
I just have to use `TERM=xterm-256color` when using dosemu in screen. And have to update my applications to use the correct codes for F11/F12 and detect 16.10 using 16.09, which also implies filtering xxE0 codes to the xx00 that Insight expects.

**Comment by stsp** [comment]
> I just have to use TERM=xterm-256color when using dosemu in screen.

But IIRC you were saying there are
still inconsistencies between -t and -kt.
How should I see these?

> And have to update my applications to use the correct codes

Don't you like to update your apps to
use only the correct codes? :)
Well, I already know the answer is "no"
as yesterday you didn't want to use the
correct cursor position codes.

**Comment by ecm-pushbx** [comment]
> > I just have to use TERM=xterm-256color when using dosemu in screen.
> 
> But IIRC you were saying there are still inconsistencies between -t and -kt. How should I see these?

Left Arrow sends a "D" to keybtest if I use `TERM=screen-256color dosemu -dumb -td -kt` in screen.

Checking with the patched ke10test I actually get two keypress codes for Left Arrow: `1A00` then `2044 "D"`. Unpatched keybtest only displays `2044 "D"`.

I just checked, if I run `TERM=screen-256color dosemu -dumb -td -kt` but **not** in screen, the same error condition occurs.

> > And have to update my applications to use the correct codes
> 
> Don't you like to update your apps to use only the correct codes? :) Well, I already know the answer is "no" as yesterday you didn't want to use the correct cursor position codes.

I just like consistency and my use cases being supported when there is no need to break them.

**Comment by stsp** [comment]
> Left Arrow sends a "D" to keybtest if I use TERM=screen-256color dosemu -dumb -td -kt in screen.

Yes, this is reproducible.
Is there an inconsistency w/o weird
TERM though?

> I just like consistency and my use cases being supported when there is no need to break them.

If they break from every bug fix, then
its not a consistency. Also currently we
don't yet know what "breaks". The
difference between -t and -kt may be
a clue.

**Comment by ecm-pushbx** [comment]
> > Left Arrow sends a "D" to keybtest if I use TERM=screen-256color dosemu -dumb -td -kt in screen.
> 
> Yes, this is reproducible. Is there an inconsistency w/o weird TERM though?

The F11/F12 situation is a bit weird, as mentioned I used `dosemu -t` to develop Insight and it seemed to give 5400h and 5500h for those keys (on 16.00 call). But that seems to have been a bug in itself, not what was meant to happen.

**Comment by stsp** [comment]
So arrow under screen-256color is the
only difference right now between -t and -kt,
correct?

**Comment by ecm-pushbx** [comment]
Yes.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by ecm-pushbx** [comment]
Thanks, I do get arrow keys with the default TERM now. However, using either 16.00 or 16.10 the F11 and F12 keys send 5400 and 5500 keypresses again. Both in `-dumb -td -kt` and `-t` mode. Not really a problem, just odd.

**Comment by stsp** [comment]
With bad TERM only, right?
I think "again" does not apply.
I checked the prev revision and
got the same.

**Comment by stsp** [comment]
Not all terminals support F12.
And the particular one you select,
reports Shift-F2 instead.
There is nothing to fix, just don't
use broken software, old terminals
(or emulators of old terminals)
and so on.

**Comment by ecm-pushbx** [comment]
> With bad TERM only, right? I think "again" does not apply. I checked the prev revision and got the same.

Correct, `TERM=screen-256color` sends the 5x00 codes for F11 and F12, `TERM=xterm-256color` sends the 8x00 codes (on 16.10 call).

> Not all terminals support F12.
And the particular one you select,
reports Shift-F2 instead.
There is nothing to fix, just don't
use broken software, old terminals
(or emulators of old terminals)
and so on.

Don't have much of a choice but it's fine either way.
