### ISSUE TITLE
"uires DOSEMU to run, aborting" when trying to start programs on NFS mount

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#2031]
**Describe the bug**
When I try to run a program from an NFS mount, I get this:
![Screenshot_20230625_184222](https://github.com/dosemu2/dosemu2/assets/877112/6ff0823b-85a7-45e4-b271-9b444ff2cb3f)

**To Reproduce**
1. Run a program on an NFS mounted path

**Attach program/game binaries or provide an URL**
n.a.
I tried various programs, they all show the same.

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/11860288/boot.log)

**A regression?**
yes

**Additional info**
Local programs run without issues.

**Comment by stsp** [comment]
Please provide `-D9+Dd` log.

**Comment by jschwartzenberg** [comment]
[boot.log](https://github.com/dosemu2/dosemu2/files/11860321/boot.log)

**Comment by stsp** [comment]
Should now be fixed, please check.

**Comment by stsp** [comment]
`"This program requires DOSEMU to run, aborting"`
Not sure how this msg appeared here.

**Comment by jschwartzenberg** [comment]
Still the same, here a new log:
[boot.log](https://github.com/dosemu2/dosemu2/files/11860967/boot.log)

**Comment by stsp** [comment]
Should now be fixed. :)

**Comment by jschwartzenberg** [comment]
Indeed! Thanks!!
