### ISSUE TITLE
Passing text with `-input` doesn't work correctly

### ISSUE THREAD

**Issue by ecm-pushbx** [dosemu2/dosemu2#2071]
**Describe the bug**
In one of my scripts I am trying to pass some keyboard input to a DOS application: https://hg.pushbx.org/ecm/ldosboot/file/007ddb5647c7/test/test.sh#l448

```
    timeout --foreground 10 "$DOSEMU" -input \
     "$(echo -ne "boot $options_ldebug_unit"'\rif (rc) then boot quit\rq\r')" \
     -I "floppy { device diskldbg.img }" \
     -I "$dosemu_category { $dosemu_device $name.img }" \
     -A -dumb 2> result.err > result.log < /dev/null
```

Expanding the various variables we get a command like this:

```
dosemu  -input "$(echo -ne 'boot fdb\rif (rc) then boot quit\rq\r')" \
  -I 'floppy { device diskldbg.img }' -I 'floppy { device diskette.img }' -A -dumb
```

The desired outcome is to send keyboard input to the dosemu2 machine, running my debugger. This is to include some CR bytes to submit the command.

What I get instead:

```
ldosboot/test$ dosemu  -input "$(echo -ne 'boot fdb\rif (rc) then boot quit\rq\r')" \
  -I 'floppy { device diskldbg.img }' -I 'floppy { device diskette.img }' -A -dumb
if not found
ifrecognized argument: fdb
```

**To Reproduce**
Run the above command. Files are provided in the test directory (next section).

**Attach program/game binaries or provide an URL**
https://pushbx.org/ecm/test/20230812/ Two image files that should work.

**Attach the log**
[boot.log](https://github.com/dosemu2/dosemu2/files/12327727/boot.log)

**A regression?**
4beffeff4 and 3b250d8d0 on the amd64 Debian 12 machine fail too.

9cf2b7560 on the server (amd64 Debian 11) works:

```
ldosboot/test$ dosemu  -input "$(echo -ne 'boot fdb\rif (rc) then boot quit\rq\r')" \
>   -I 'floppy { device diskldbg.img }' -I 'floppy { device diskette.img }' -A -dumb
ERROR: alsa_midi (ALSA lib): seq_hw.c:466:(snd_seq_hw_open) : No such file or directory open /dev/snd/seq failed
dosemu2 2.0pre8-20191102-1332-g9cf2b7560
Configured: 2022-03-29 20:33:55 +0200
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org


-boot fdb
-if (rc) then boot quit
-q
Test writer loaded successfully. Quitting the machine.
```

4beffeff4 on the server seems to fail, too:

```
ldosboot/test$ ~/local.new/bin/dosemu  -input "$(echo -ne 'boot fdb\rif (rc) then boot quit\rq\r')"   -I 'floppy { device diskldbg.img }' -I 'floppy { device diskette.img }' -A -dumb
ifrecognized argument: fdb
For passing DOS command use -E
```

This is the output of the various ldosboot tests, with [ldosboot revision 9c4923acc2be](https://hg.pushbx.org/ecm/ldosboot/rev/9c4923acc2be), on the server. Default `dosemu` is 9cf2b7560, the `~/local.new/bin/dosemu` is 4beffeff4.

The next revision of ldosboot has some other problems, see https://github.com/dosemu2/dosemu2/discussions/2070

```
ldosboot/test$ ./test.sh diskette direct
success
ldosboot/test$ ./test.sh hdimage direct
Error: dosemu lacks support for -C4 switch
ldosboot/test$ ./test.sh diskette
success
ldosboot/test$ ./test.sh hdimage
success
ldosboot/test$ DOSEMU=~/local.new/bin/dosemu ./test.sh diskette direct
success
ldosboot/test$ DOSEMU=~/local.new/bin/dosemu ./test.sh hdimage direct
success
ldosboot/test$ DOSEMU=~/local.new/bin/dosemu ./test.sh diskette
failure, log contains:
Result log file empty, dosemu error?
ldosboot/test$ DOSEMU=~/local.new/bin/dosemu ./test.sh hdimage
failure, log contains:
Result log file empty, dosemu error?
ldosboot/test$ 
```

**Additional info**
On the local machine, dosemu2 is set up according to https://pushbx.org/ecm/dokuwiki/doku.php?id=blog:pushbx:2023:0706_how_to_set_up_dosemu2_freedos_and_ldebug

On the server, similar FreeDOS kernel and FreeCOM builds are in use.

**Comment by ecm-pushbx** [comment]
9cf2b7560 on the local machine does pass `-input` content correctly, as well, however it fails this test because of a message about mismatching directories. But this definitely says it is a regression. Output:

```
ldosboot/test$ ~/proj/dosemu2-9cf2b75/bin/dosemu  -input "$(echo -ne 'boot fdb\rif (rc) then boot quit\rq\r')"   -I 'floppy { device diskldbg.img }' -I 'floppy { device diskette.img }' -A -dumb
ERROR: Directory /usr/local/share/dosemu/fdboot does not exist
ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.
ERROR: dosemu2 commands not found at /usr/local/share/dosemu/dosemu2-cmds-0.2

Welcome to DOSEMU2
This program is  distributed  in  the  hope that it will be useful,
but  WITHOUT  ANY  WARRANTY;   without even the implied warranty of
MERCHANTABILITY  or  FITNESS FOR A PARTICULAR PURPOSE. See the files
COPYING for more details.
Press ENTER to confirm, and boot DOSEMU2, or [Ctrl-C] to abort
boot fdb
dosemu2 2.0pre8-20191102-1332-g9cf2b7560
Configured: 2023-08-12 18:02:19 +0200
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org


-if (rc) then boot quit
-q
dosemu2 2.0pre8-20191102-1332-g9cf2b7560
Configured: 2023-08-12 18:02:19 +0200
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org


-
```

Actually, that message only appeared on the first run. A subsequent run with this revision works fine, as expected for the regression:

```
ldosboot/test$ ~/proj/dosemu2-9cf2b75/bin/dosemu  -input "$(echo -ne 'boot fdb\rif (rc) then boot quit\rq\r')"   -I 'floppy { device diskldbg.img }' -I 'floppy { device diskette.img }' -A -dumb
ERROR: Directory /usr/local/share/dosemu/fdboot does not exist
ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.
ERROR: dosemu2 commands not found at /usr/local/share/dosemu/dosemu2-cmds-0.2
dosemu2 2.0pre8-20191102-1332-g9cf2b7560
Configured: 2023-08-12 18:02:19 +0200
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org


-boot fdb
-if (rc) then boot quit
-q
Test writer loaded successfully. Quitting the machine.
```

**Comment by stsp** [comment]
You need to find a way to reproduce
that reliably.

**Comment by ecm-pushbx** [comment]
Can you not reproduce with this command? `dosemu  -input "$(echo -ne 'boot fdb\rif (rc) then boot quit\rq\r')" -I 'floppy { device diskldbg.img }' -I 'floppy { device diskette.img }' -A -dumb`

**Comment by ecm-pushbx** [comment]
It is reproduceable 100% for me.

**Comment by ecm-pushbx** [comment]
Dropping the diskette images and `-A` switch also can reproduce it, for example:

```
test$ dosemu -dumb -quiet -input "foo"
C:\>foo"
```

The first quote mark probably is intercepted by the FreeDOS kernel boot wait (it seems to eat a keypress if one is available). The second quote mark **should not** appear on the command line.

I also get a superfluous quote mark if I try to pass `echo -ne` output to the `-input` switch:

```
test$ dosemu -dumb -quiet -input "$(echo -ne 'foo\rbar\r')"
C:\>foo
Bad command or filename - "foo".
C:\>bar
Bad command or filename - "bar".
C:\>"
```

**Comment by ecm-pushbx** [comment]
The exact same input, but without the diskette images and `-A` switch, also causes a similar error:

```
test$ dosemu  -input "$(echo -ne 'boot fdb\rif (rc) then boot quit\rq\r')" -dumb
if not found
ifrecognized argument: fdb
```

**Comment by stsp** [comment]
What is "a message about mismatching directories"?

**Comment by ecm-pushbx** [comment]
This part shown by dosemu2 9cf2b7560 on my first boot on the local machine:

```
ERROR: Directory /usr/local/share/dosemu/fdboot does not exist
ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.
ERROR: dosemu2 commands not found at /usr/local/share/dosemu/dosemu2-cmds-0.2

Welcome to DOSEMU2
This program is  distributed  in  the  hope that it will be useful,
but  WITHOUT  ANY  WARRANTY;   without even the implied warranty of
MERCHANTABILITY  or  FITNESS FOR A PARTICULAR PURPOSE. See the files
COPYING for more details.
Press ENTER to confirm, and boot DOSEMU2, or [Ctrl-C] to abort
boot fdb
dosemu2 2.0pre8-20191102-1332-g9cf2b7560
Configured: 2023-08-12 18:02:19 +0200
Please test against a recent version before reporting bugs and problems.
Get the latest code at http://stsp.github.io/dosemu2
Submit Bugs via https://github.com/stsp/dosemu2/issues
Ask for help in mail list: linux-msdos@vger.kernel.org
```

It actually appears to be two separate messages, the directory-related warnings as well as the "Welcome to DOSEMU2" message. The latter disappeared after the first run. However, all of this is irrelevant to this bug report.

**Comment by ecm-pushbx** [comment]
> This part shown by dosemu2 https://github.com/dosemu2/dosemu2/commit/9cf2b756098eb20f787670cdb7e560af53e2f3a5 on my first boot on the local machine:

Note that I expect a failure like this, as I did not `make install` this revision to anywhere. I just ran `~/proj/dosemu2-9cf2b75/bin/dosemu` with all the other things set up as for `sudo make install` of the most recent revision 28f8df492.

As mentioned, this is not relevant, it is only relevant that the older revision handles `-input` as expected and the newer revisions fail.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by ecm-pushbx** [comment]
Still get an error like before. Did `git pull`, `make`, `sudo make install`:

```
~/proj/dosemu2$ git describe
2.0pre9-dev-1400-g5313c7c64
```

Result:

```
~/proj/ldosboot/test$ dosemu  -input "$(echo -ne 'boot fdb\rif (rc) then boot quit\rq\r')" -dumb
if not found
ifrecognized argument: fdb
```

**Comment by stsp** [comment]
Should now work.

**Comment by ecm-pushbx** [comment]
It does work if I comment out the check you added in https://github.com/dosemu2/dosemu2/commit/5313c7c64b36afef8f6f29ae70f0898321e898ba#diff-93bf7557dcc94d1789f80fc2cff4c9adafd74615163c9fb2e0b996c33a99e308R157

Running without the diskette images and without the switch `-A` it always works now, but when I boot the debugger then apparently `start_pre_strokes` is never called. Can you give me an option to work around this? (Eg add a dosemu2 interrupt function that would call `start_pre_strokes` ?)

**Comment by ecm-pushbx** [comment]
I don't currently need this. But, your most recent change also appears to still fail if I pass a tab to the input:

```
$ dosemu -dumb -td -kt -input "$(echo -ne 'foo\tbaz\rbar\r')"
 not found
barecognized argument: baz
```

**Comment by ecm-pushbx** [comment]
Same if I pass an LF:

```
$ dosemu -dumb -td -kt -input "$(echo -ne 'foo\nbaz\rbar\r')"
 not found
barecognized argument: baz
```

**Comment by stsp** [comment]
Things will work if you stop passing
the prestroke string via echo.
The check is needed or the first char
is swallowed.

**Comment by stsp** [comment]
Are you starting the debugger directly
from a boot sector? If so, you need to
enable prestrokes by hands, doing this:
```
mov dx,0
mov ax,0ae00h
int 2fh
```

**Comment by ecm-pushbx** [comment]
> Things will work if you stop passing the prestroke string via echo.

Oh, I didn't know that `-input` parses backslash escapes.

> Are you starting the debugger directly from a boot sector?

Yes, exactly.

> If so, you need to enable prestrokes by hands, doing this:
> 
> ```
> mov dx,0
> mov ax,0ae00h
> int 2fh
> ```

This is where that function seems to be implemented: https://github.com/dosemu2/dosemu2/blob/a17d39035bf578ea3a8e7325bcee19fdef687632/src/base/core/int.c#L2970

Will this not interfere with other effects of dos_post_boot, though? https://github.com/dosemu2/dosemu2/blob/a17d39035bf578ea3a8e7325bcee19fdef687632/src/base/core/int.c#L2842

I'd feel safer if there was a function to call only start_pre_strokes. Ideally on the int 0E6h interface rather than int 2Fh?

**Comment by stsp** [comment]
OK,  done.

**Comment by ecm-pushbx** [comment]
It works! Thanks a lot. I added this to the debugger's init after dosemu is detected: https://hg.pushbx.org/ecm/ldebug/rev/0ace864f1d54

**Comment by stsp** [comment]
So the next time you think whether d2 is
full vm or a software layer, think of all these
extensions and apis. :)

**Comment by ecm-pushbx** [comment]
> So the next time you think whether d2 is full vm or a software layer, think of all these extensions and apis. :)

I do think the integration is superb, but in my nomenclature dosemu2 is also a VM, too. In my view that doesn't conflict with terminal output modes or DOS drives via file system redirector or even the native DPMI (when no KVM is available).

**Comment by stsp** [comment]
Thats true and I said nonsense by typing
"full vm" above. Iirc last time we talked
about "full emulator".
