### ISSUE TITLE
terminal: keyboard hangs for a short time when keystrokes come in too fast

### ISSUE THREAD

**Issue by severach** [dosemu2/dosemu2#2292]
**Describe the bug**
Keystrokes too fast hang the keyboard handler.

**To Reproduce**
`dosemu -t`. At DOS prompt, mash keys as fast as possible. A few will show then the keyboard hangs for a while. 

**Additional info**
Moving the mouse can clear the keyboard handler hang and cause the remaining keys to show.

**Comment by stsp** [comment]
I can just hold the key to get auto-repeat.
It only stops when comcom64 buffer
is full.

**Comment by severach** [comment]
Hit two keys at the same time so they come in very fast, much faster than auto repeat or any human can type. Put 2 fingers together and hit WQ over and over.

**Comment by stsp** [comment]
Is this specific to -t mode?

**Comment by severach** [comment]
Yes. The windowed version has no problem with fast key hits.

Ok, I'm wrong. The windowed version does it too. The processing is much faster so it takes a lot more and faster key hits to get it to jam up. I put 4 fingers together on two hands and go back and forth on Quer, Uiop. It doesn't hang either. It just skips the keys if they come in too fast.

Ok, I'm wrong again. Turns out it's a limitation of the Dell MW437 USB keyboard. Mashing the Dell E6440 laptop's keyboard never drops keys.

Now I'm really confused. Mashing WQ on the laptop keyboard in `dosemu -t` does not hang. But if I ssh to 127.0.0.1 then `dosemu -t` the laptop keyboard does hang. Let's see if I can summarize this.

Windowed: USB keyboard loses keys but doesn't hang, laptop keyboard does not lose keys or hang. This is probably the keyboard.

`dosemu -t` in Gnome Terminal: USB keyboard loses keys but doesn't hang, laptop keyboard does not lose keys or hang.

`dosemu -t` in Gnome Terminal through ssh. All keyboards hang and lose keys equally.

**Comment by stsp** [comment]
I believe it is now fixed, at least
partially. Please check.

**Comment by severach** [comment]
The hang is gone. Keys mashed fast still get held up in the queue. Hitting a key lets them out a few at a time. Moving the mouse lets them all out.

This gets rid of the main problem where hitting two keys quickly hangs the keyboard.

**Comment by stsp** [comment]
I think this is now fixed.
