### ISSUE TITLE
$_cpu_vm = "vm86" results in unexpected CPU exception 0x0e err=0x00000006 cr2=32cXXXXX while in vm86 (DOS) when running various programs

### ISSUE THREAD

**Issue by jschwartzenberg** [dosemu2/dosemu2#2447]
**Describe the bug**
When I run a game with `$_cpu_vm = "vm86"` (or leaving this out as it's picked by default) I get:
```
ERROR: unexpected CPU exception 0x0e err=0x00000006 cr2=32c9f000 while in vm86 (DOS)
Terminated with signal 4
```
The value of `cr2` changes, but always starts with `32c`.
Setting `$_cpu_vm = "emulated"` allows the game to run, but this is rather slow.

**To Reproduce**
Run a game such as Crystal Caves, Duke Nukem or Jill of the Jungle.

**Attach program/game binaries or provide an URL**
I'll put something here if needed, but it seems to happen with almost anything.

**Attach the log**
[boot.log](https://github.com/user-attachments/files/19721773/boot.log)

**A regression?**
Yes.

**dosemu2 origins**
Self-built.

**Additional info**
Again 32-bit. Would it help if I'd create a QEMU VM with a vm86 enabled kernel in it? I guess that would help to reproduce this. SSH should work too, but I guess it will be hard to keep vm86 alive at all if you have to SSH into my laptop each time it breaks :)

**Comment by stsp** [comment]
Yep, vm should be fine,
bisect is even better if its
a recent regression, i.e.
your prev half-year-old
build didn't have it.

**Comment by stsp** [comment]
> The value of cr2 changes, but always starts with 32c.

But in the log:
`ERROR: unexpected CPU exception 0x0e err=0x00000006 cr2=3309f000 while in vm86 (DOS)`
so no.

**Comment by stsp** [comment]
Please re-do the log.

**Comment by jschwartzenberg** [comment]
> > The value of cr2 changes, but always starts with 32c.
> 
> But in the log: `ERROR: unexpected CPU exception 0x0e err=0x00000006 cr2=3309f000 while in vm86 (DOS)` so no.

It always starts with a 3 then? Maybe just a coincidence yep... :)


> Please re-do the log.

[boot.log](https://github.com/user-attachments/files/19724220/boot.log)


> Yep, vm should be fine, bisect is even better if its a recent regression, i.e. your prev half-year-old build didn't have it.

I only compiled my own kernel for vm86 support recently. I'll look into doing both though.

**Comment by jschwartzenberg** [comment]
> Yep, vm should be fine, bisect is even better if its a recent regression, i.e. your prev half-year-old build didn't have it.

I tried to share a file by mail with a VM image. Let me know if you can access it. If it asks for a password, try `"iYLIF6X-=`.

**Comment by stsp** [comment]
Yes, downloaded.

**Comment by stsp** [comment]
Does this vm even have dosemu2
somewhere?

**Comment by jschwartzenberg** [comment]
No, I was considering including everything (also for rebuilding the kernel), but the image was quickly becoming quite large. I thought it would be easier to provide a small image as it should be easy to install everything anyhow.

Let me know if there are any issues or I should provide something that's missing now.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by jschwartzenberg** [comment]
I'll still seeing this on my laptop: [boot.log](https://github.com/user-attachments/files/19831838/boot.log)

I'll try to reproduce this in QEMU.

**Comment by jschwartzenberg** [comment]
I can't reproduce this is in QEMU either... I'll investigate a bit more but I guess the best will be to provide SSH.

Some more differences. I had installed freecom on my laptop to allow easier testing with older dosemu2 versions. When I remove it now, dosemu2 fails with "Unable to allocate stack" on my laptop. In QEMU everything works fine with/without freecom.

In QEMU, I do get this floating point exception a bit further in Crystal Caves: [boot.log](https://github.com/user-attachments/files/19839033/boot.log) (should be a new bug?)

**Comment by jschwartzenberg** [comment]
SSH would work now with the same info as the previous time.

**Comment by stsp** [comment]
There is a problem with comcom64:
```
$ djstubify -i comcom64.exe 
dj64 file format
Overlay 0 (i386/ELF DOS payload) at 87173, size 80728
Overlay 1 (i386/ELF host payload) at 23440, size 177476
Stub version: 6
Stub flags: 0x8020
```

And on my PC:
```
$ djstubify -i comcom64.exe 
dj64 file format
Overlay 0 (i386/ELF DOS payload) at 91285, size 5228
Overlay 1 (x86_64/ELF host payload) at 23440, size 87144
Overlay 2 (x86_64/ELF debug info) at 110584, size 212632
Stub version: 6
Stub flags: 0x8b27
```

The main difference is flags.
Where have you got this
comcom64?

**Comment by jschwartzenberg** [comment]
I built it from Git using `debuild -us -uc` and then installing the package.

**Comment by stsp** [comment]
But for that to work, you had
to also build djstub and dj64dev.
Please list the commits of all 3.

**Comment by jschwartzenberg** [comment]
Indeed, seems that comcom64 works on QEMU though.

djstub: 0ddcccccffe8c40c8e1a6c9153b7bd6199676b9c
dj64dev: 941693f22f2482c79c1fccae1abd1a866b14a3b9
comcom: 55c323f5715db0e580e4f3be94c34ecee7152f6d (I updated this one to latest when I noticed problem, but didn't make a difference)

**Comment by stsp** [comment]
Could you please re-do that
procedure after updating all
3 from git? I don't have root
on your machine to do that.

**Comment by jschwartzenberg** [comment]
Done! All are the latest version now.

**Comment by stsp** [comment]
So what doesn't work now?

**Comment by jschwartzenberg** [comment]
When I run dosemu with comcom and `$_cpu_vm_dpmi = native` and `-no-priv-sep`. It fails with `Unable to allocate stack`.

Crystal Caves still causes the exception I opened this ticket for.

And `unix -s <any script>` causes the assertion error (from the other ticket, #2446).

**Comment by stsp** [comment]
Write these games to my drive_c.
Please reproduce `unix -s` problem
with my build.

**Comment by jschwartzenberg** [comment]
Crystal Caves is in `cc1`.
Put the log for the `unix -s` issue in the other ticket.

**Comment by stsp** [comment]
It no longer logs me in, have
you changed the password?

**Comment by jschwartzenberg** [comment]
No, I didn't change anything. I'll try to restart the laptop.

Should work now.

**Comment by stsp** [comment]
Thanks, although I suspect the
problem was on my side. It
seems dosemu2 reprogrammed
the terminal, so when I pasted
the password with mouse, it
didn't actually paste. But since
its an invisible process, I had
no idea. :)

**Comment by stsp** [comment]
Well if its a gfx program, then
I need vnc. `ssh -X` is just
unacceptably slow.

**Comment by jschwartzenberg** [comment]
I installed Xvnc. Running `Xvnc :1` and using `-L <local port>:localhost:5901` with ssh should do the trick.

**Comment by stsp** [comment]
This machine has only 512Mb.
Please do:
`echo 1 >/proc/sys/vm/overcommit_memory`

**Comment by jschwartzenberg** [comment]
Done!

**Comment by stsp** [comment]
`echo 0 > /proc/sys/kernel/yama/ptrace_scope`

**Comment by jschwartzenberg** [comment]
Done!

**Comment by stsp** [comment]
Managed to boot in gfx mode
once, by reducing dpmi_base.
It appears we can exhaust
entire mmap space on a 32bit
system.

**Comment by jschwartzenberg** [comment]
Testing the latest now, I see this pass by on start-up:
```
julius@kont:~/checkouts/dosemu2$ dosemu
ERROR: using outdated config file /home/julius/.dosemurc
Security warning: native DPMI mode is insecure, adjust $_cpu_vm_dpmi
../../../src/include/memory.h:205:10: runtime error: applying non-zero offset to non-null pointer 0x8d200000 produced null pointer
    #0 0xb209ded0 in MEM_BASE32 ../../../src/include/memory.h:205
    #1 0xb209ded0 in copy_to_dpmi /home/julius/checkouts/dosemu2/src/plugin/dnative/dnative.c:119
    #2 0xb209f52a in dpmi_return /home/julius/checkouts/dosemu2/src/plugin/dnative/dnative.c:276
    #3 0xb20a2a89 in dosemu_fault1 /home/julius/checkouts/dosemu2/src/plugin/dnative/sigsegv.c:301
    #4 0xb20a2d26 in dosemu_fault0 /home/julius/checkouts/dosemu2/src/plugin/dnative/sigsegv.c:362
    #5 0xb20a31a3 in dosemu_fault /home/julius/checkouts/dosemu2/src/plugin/dnative/sigsegv.c:382
    #6 0xb7f0b58f  (linux-gate.so.1+0x58f)
```

Crystal Caves doesn't run yet against a local X11 server: [boot.log](https://github.com/user-attachments/files/19854847/boot.log)

**Comment by stsp** [comment]
Is this error consistent?

**Comment by stsp** [comment]
Could you please check the
error now?

**Comment by jschwartzenberg** [comment]
That runtime pointer error is gone now.

Here is the current `boot.log` with Crystal Caves: [boot.log](https://github.com/user-attachments/files/19855901/boot.log)

**Comment by stsp** [comment]
Should now be fixed.

**Comment by jschwartzenberg** [comment]
Indeed working now!! Great!! I'll be able to do some more benchmarking now. Might graphics indeed be faster without vm86?

**Comment by stsp** [comment]
Yes, should be faster with
KVM, and mode-X is faster
with JIT. Not so much after
#463 is fixed, but that just
means I dispatch jit when
needed for speed-up.
