### ISSUE TITLE
Crash in simx86 JIT: “ERROR: Fault 13 in jit-compiled code” / ERROR: Bad exec address 0x78cb7f6ef711

### ISSUE THREAD

**Issue by haenschen** [dosemu2/dosemu2#2708]
**Describe the bug**
When running my legacy DOS application under dosemu2 built from current git sources, dosemu2 crashes shortly after the program starts. With `$_cpu_vm=emulated` I get a ERROR: Fault 13 in jit-compiled code, with `$_cpu_vm=kvm` it's ERROR: Bad exec address 0x78cb7f6ef711.

Furthermore, if I do `$_cpuemu = (1)` (interpreter) it doesn't seem to happen.

**To Reproduce**
At the moment I can't trace it back to specific steps but it happens so regularly that I can provoke it to occur seemingly random. I attached 3 logs from different attempts.

**Attach program/game binaries or provide an URL**
Can provide per mail

**Attach the log**

[boot.log](https://github.com/user-attachments/files/24020328/boot.log)

[boot_1.log](https://github.com/user-attachments/files/24020329/boot_1.log)

[boot_kvm.log](https://github.com/user-attachments/files/24020434/boot_kvm.log)

**A regression?**
Worked in dosemu2-2.0pre6 with ubuntu 16.04

**dosemu2 origins**
From git

```
./default-configure --disable-dj64 --disable-searpc
Enabling plugins: 
	X 
	Xkmaps 
	alsa 
	charsets 
	console 
	dnative 
	doscmd 
	dosdrv 
	extra_charsets 
	fdpp 
	json 
	midimisc 
	modemu 
	msdos 
	periph 
	sdl

configure: WARNING: dj64dev not available!

configure: WARNING: searpc not available!

```

**Additional info**
freecom

Tried with emulated and kvm, see logs

**I can stick to interpreter for my use case to avoid this crash.**

**Comment by bartoldeman** [comment]
This is a recurring IRQ13 (FPU exception handler), which seems to eventually blow up (as it seems to retrigger multiple times)
If you can email it (`<github-user-name>`@gmail.com) I can have a look.

**Comment by stsp** [comment]
I've fixed the crash, although
I suspect its not the same crash
that you had (mine was unrelated
to FPU). So if still crashes - please
proceed with @bartoldeman

**Comment by bartoldeman** [comment]
yes `ecx` definitely is clobbered, I forgot to put it back :(
But that doesn't explain the issue with KVM; it's possible that now the program works fine with JIT (as it works ok with sim) but not with KVM.

**Comment by stsp** [comment]
But KVM uses JIT these days:
even if prejitter is not the cause,
then it switches to JIT for
planar GFX.

**Comment by stsp** [comment]
Note that `$_cpuemu` setting
also affects whatever KVM uses.
It can still use SIM.

**Comment by haenschen** [comment]
Now it won't crash anymore but log still shows `coprocessor exception, calling IRQ13` with kvm and emulated. If this is still of interest I will prepare test case and email bart.

[boot_emulated.log](https://github.com/user-attachments/files/24036269/boot_emulated.log)
[boot_kvm.log](https://github.com/user-attachments/files/24036268/boot_kvm.log)

**Comment by stsp** [comment]
If the program works fine,
then its of no interest.

**Comment by haenschen** [comment]
Now I got a crash again :/
But at the moment I can't reproduce it persistent enough to bother bart with testing  😅 

Can I log/strace something more?

[boot.log](https://github.com/user-attachments/files/24036951/boot.log)

**Comment by stsp** [comment]
Yes, still the crash from Exec_x86()

**Comment by stsp** [comment]
Please see if this changes
anything:
```
diff --git a/src/base/emu-i386/simx86/econfig.h b/src/base/emu-i386/simx86/econfig.h
index f84d23012..92c6be5d0 100644
--- a/src/base/emu-i386/simx86/econfig.h
+++ b/src/base/emu-i386/simx86/econfig.h
@@ -55,7 +55,7 @@
 #undef DEBUG_TREE
 #define DEBUG_TREE_FILE        "/DOS/treedump.log"
 
-#define        USE_LINKER      1       // 0 or 1
+#define        USE_LINKER 0
 #undef DEBUG_LINKER
 #undef SHOW_STAT
 ```

**Comment by haenschen** [comment]
Yes, with 

`USE_LINKER 0
`

it seems stable. Furthermore I think I have a test case ready which allows to reproduce the crash consistently.


[boot_linker_0.log](https://github.com/user-attachments/files/24152303/boot_linker_0.log)
[boot_linker_1.log](https://github.com/user-attachments/files/24152304/boot_linker_1.log)

**Comment by stsp** [comment]
Have you sent it to Bart?

**Comment by haenschen** [comment]
Just now I did :) @bartoldeman

**Comment by stsp** [comment]
Any news?

**Comment by bartoldeman** [comment]
I've got the test case (somehow it ended up in my spam folder) but haven't worked on it yet, will take a look today.

**Comment by stsp** [comment]
Bisect: bf9352e52

**Comment by stsp** [comment]
Seems like BreakNode() became
ineffective if the node is linked.
It keeps executing instead of a
break.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by stsp** [comment]
Although I am not entirely
sure I fixed your problem.
I had a different manifestation
of it (assertion failure), but
I hope its now the same thing.

**Comment by bartoldeman** [comment]
I got the test case but haven't been able to reproduce the crash. But I did see the SIGFPE being handled incorrectly, so that's why I filed #2725 

So for the BreakNode failure, I should apologize for the missing changelog, I am somewhat surprised since I thought it was just an optimization that is no longer valid, since if the last instruction in the sequence is `JMP_INDIRECT`, `TheCPU.key` is not reliable when for removal of the node. I'll have to carefully look at that code to play the buggy scenario then.

**Comment by haenschen** [comment]
With latest devel it still crashes for me at the same actions. 

[boot_2.log](https://github.com/user-attachments/files/24279943/boot_2.log)
[boot_1.log](https://github.com/user-attachments/files/24279944/boot_1.log)

**Comment by stsp** [comment]
The bug was that you set
TheCPU.err = EXCP_BREAKNODE
but if you break past the node,
then nothing breaks, and yet
you get the stalled exit code.
When it actually exits much
later, it still thinks it needs to
wipe the just-broken node, but
key have changed etc, so it
just crashes.

**Comment by stsp** [comment]
> With latest devel it still crashes for me at the same actions.

Ok, seems we have lots
of regressions around this
topic.

**Comment by stsp** [comment]
Likely now fixed by #2725 ?

**Comment by haenschen** [comment]
No, but different error now :)

```
coprocessor exception, calling IRQ13
ERROR: FPU IRQ cannot be injected (0 0), bye
leavedos(raise_fpu_irq:328|0) called - shutting down
```
[boot.log](https://github.com/user-attachments/files/24280006/boot.log)

**Comment by bartoldeman** [comment]
@haenschen it looks like the way your test case works is depending on the contents of the `auftrag` directory. What I'm getting is that I can press F10 forever and it never crashes, although sometimes the is like a 20 second wait before I can press F10 again.

**Comment by bartoldeman** [comment]
I wonder if the auftrag directory has somewhat different contents between runs, and if there is a reference I can use, as I tried to reset to the one in your zip but it didn't help.

**Comment by stsp** [comment]
There is an FPU error in #2724 
which is relatively easy to
reproduce. Just needs to
start the thing a few times.

**Comment by haenschen** [comment]
@bartoldeman Yes, content in the auftrag directory will change. You need to delete the auftrag directory and copy it from the reference again as „progress“ is stored in new files which won‘t be overwritten with a simple copy.

**Comment by haenschen** [comment]
But I don‘t know why it won‘t crash for you as I can reproduce it consistently with the test case I provided :(

**Comment by stsp** [comment]
Can you check the code from
#2728 please? It probably fixes
also this.

**Comment by stsp** [comment]
Which is now in devel.

**Comment by haenschen** [comment]
Unfortunately not. Interpreter still works.
Sometimes it's
```
ERROR: Bad exec address 0x200246

Speicherzugriffsfehler (Adresse ist nicht mit dem Objekt verbunden [0x200246])
```

and sometimes

`Invalid machine instruction (unauthorized operand [0x761cf862fbe2])`

[boot.log](https://github.com/user-attachments/files/24296114/boot.log)

[boot_1.log](https://github.com/user-attachments/files/24296117/boot_1.log)

**Comment by stsp** [comment]
I think you need to send
the test-case to me then.
If Bart can't reproduce,
then maybe I can.

**Comment by haenschen** [comment]
Okay, I forwarded my mail, please check spam :)

**Comment by stsp** [comment]
Not even in spam.
Reproduced from the first
time, but after that, it started
to hang, as Bart described.

**Comment by stsp** [comment]
I know how to reproduce
100% reliably. You just need
to wait 20sec when you see
"START MOVING", and the
next time "GO TO MEAS".
Just wait until these messages
disappear, and only then
keep pressing F10.

**Comment by bartoldeman** [comment]
@stsp how were you able to do a bisect before getting the testcase?

I reproduced it (by using comcom32 instead of comcom64 for some reason) and have a fix but I think I need to revert your breaknode revert.

Basically what happens is that instruction
```  0002f683: 2edd3e7026        2cfb:26d3 fstsw cs:[2670]```
causes a node hit without cpatch, so the whole page is unprotected, and simx86/sigsegv.c handled that incorrectly. We just haven't seen this yet, as all non-FP instructions that touch protected pages go via cpatch.

Getting instructions like `FST` to go via cpatch is a bit harder, either cpatch needs to be taught about those, or the up to 10 bytes need to be first stored on the host stack, and then copied to the guest memory, a bit like `write_long_double` in `fp87-sim.c`.

**Comment by stsp** [comment]
I did a bisect over the crashing
zx_emul. You likely dont have to
revert it: breaknode must not be
called when there is nothing to
break. Just unlink the node
instead, and then exit.

Вторник, 23 декабря 2025 г получено от Bart Oldeman:

**Comment by haenschen** [comment]
This is much much more stable. However, I still got a crash after a few tries

[boot.log](https://github.com/user-attachments/files/24386171/boot.log)

**Comment by haenschen** [comment]
With `$_ignore_fpe = (off)` it's fine

**Comment by haenschen** [comment]
Sorry, `$_ignore_fpe = (on)`

**Comment by andrewbird** [comment]
Slightly off topic. There's some odd chars in your log, looks like uninitialised data.
~~~
CONF(LPT0) f: (null)   c: ãàZ  t: 3  port: 0
CONF(LPT1) f: (null)   c: üàZ  t: 3  port: 0
~~~

**Comment by haenschen** [comment]
> Slightly off topic. There's some odd chars in your log, looks like uninitialised data.
> 
> ```
> CONF(LPT0) f: (null)   c: ãà��Z  t: 3  port: 0
> CONF(LPT1) f: (null)   c: ü�à��Z  t: 3  port: 0
> ```

I didn't touch parallel config so default values should be set. I haven't tried printing yet but usually I use `$_lpt1 = "lpr -l` to print via CUPS.

**Comment by andrewbird** [comment]
How curious.

**Comment by stsp** [comment]
May be interesting to get
SSH and try reproducing
the lpt corruption.

**Comment by bartoldeman** [comment]
@haenschen for the config garbage in the printer it would be useful if you could attach your `/etc/dosemu/dosemu.conf`

**Comment by bartoldeman** [comment]
And for the crash can you please run `dosemu -D+3e` and get boot.log from that : the log will be bigger but since you use KVM, the emulator log should not be excessive.

**Comment by haenschen** [comment]
Of course!

[boot_-D+3e.zip](https://github.com/user-attachments/files/24388485/boot_-D%2B3e.zip)

Please note I now changed

```
$_lpt1 = "lpr -l"
$_lpt2 = ""
```

as that's what I usually use.

[dosemu.conf.txt](https://github.com/user-attachments/files/24388492/dosemu.conf.txt)

**Comment by bartoldeman** [comment]
Thanks for the logs. I think I understand what happened and #2737 should fix the crash, but I haven't reproduced the issue now.
